### ISSUE TITLE
Editor potřebuje vidět seznam posledních komentářů

### ISSUE THREAD

**Issue by psiotwo** [kbss-cvut/termit-ui#110]
# Popis
Jako **editor slovníku**
potřebuji **vidět pojmy, které byly naposledy komentované**
abych **mohl na ně reagovat, nebo pojem na jejich základě upravit**

Potřebuji vidět pojmy naposledy komentované napříč všemi slovníky, pojmy naposledy komentované reakcemi na moje komentáře a pojmy naposledy komentované ze slovníků, které jsem vytvořil, nebo které edituji.

# Užitečnost
2. zmíněný scénář lze bez funkce realizovat, ale zdržuje mě to

**Comment by lindatothova** [comment]
# Popis
Pro **editory a komentátory** slovníku
by byla užitečná **nová záložka** v přehledu **naposledy komentovaných pojmů** na hlavní stránce. 
Záložka s názvem **S mým komentářem** by zobrazovala mnou naposledy komentované pojmy spolu **s MOJÍM posledním komentářem**.
Rozdíl oproti záložce s názvem **S reakcí na můj komentář** - ta zobrazuje mnou naposledy komentované pojmy spolu **s posledním komentářem**.
Takto by to vypadalo:

Naposledy   komentované pojmy
--
Všechny | Moje pojmy | S mým komentářem | S reakcí na můj komentář


# Využití
Viděla bych nejen poslední cizí komentář pojmu, který jsem v minulosti okomentovala, ale právě i můj poslední komentář pojmu.

# Užitečnost
2. zmíněný scénář lze bez funkce realizovat, ale zdržuje mě to

**Comment by psiotwo** [comment]
Alternativa: 
Zůstává pouze "S reakcí na můj komentář", které navíc bude ukazovat poslední komentář přihlášeného uživatelu k danému pojmu.

**Comment by psiotwo** [comment]
@lindatothova prosím vyzkoušej na dev.

**Comment by lindatothova** [comment]
Funguje správně, jen uživateli typu komentátor by se asi neměla zobrazovat prostřední záložka "Moje", protože komentátor nemůže být autorem ani editorem pojmu.
Tady by měl být popis "Zde uvidíte své naposledy komentované pojmy"
![image](https://user-images.githubusercontent.com/80691594/115892533-86772f80-a457-11eb-8dd3-5825866ba0d9.png)

Další rozvoj - nespěchá:
Šlo by na rozkliknutí tlačítka/odkazu "Zobrazit další/starší" zobrazit starší komentované pojmy?
Šlo by na detail slovníku přidat záložku "Komentáře" (+ badge s počtem) - v ní by se zobrazovaly všechny komentované pojmy v konkrétním slovníku (s posledním komentářem)?

**Comment by lindatothova** [comment]
Realizované řešení komentářů (na DEV) se kolegům líbí! Navrhujeme ještě tuto drobnou úpravu:

Jako **editor a komentátor** slovníku
potřebuji vidět **nejdříve nové komentáře**, potom starší komentáře pojmu
v záložce **Komentáře na detailu pojmu**.

Na detailu pojmu v záložce Komentáře tedy navrhujeme změnit **řazení komentářů - od nejnovějších po nejstarší.** Okno pro vytvoření nového komentáře bude seznamu komentářů předcházet.
