### ISSUE TITLE
Textová analýza textu dokumentu není plně funkční

### ISSUE THREAD

**Issue by lindatothova** [kbss-cvut/termit-ui#113]
# Popis problému
Po zmáčknutí tlačítka Analyzovat se NEzobrazí okno s výběrem slovníku, dle kterého chceme provést textovou analýzu. Analýza proběhne, ale není vidět podle jakého slovníku - určitě to není slovník patřící k dokumentu, protože ačkoliv slovník obsahuje pojmy vyskytující se v dokumentu, textová analýza žádné výskyty nenajde.

- instance: https://termit.fel.cvut.cz/dev/ipr
- dokument: Dokument pro Slovník zákona o KN
- link: https://termit.fel.cvut.cz/dev/ipr/#/resources/zakonyprolidi_cs_2013_256_v20200701.html/annotate?namespace=http://onto.fel.cvut.cz/ontologies/slovnik/slovn%C3%ADk-z%C3%A1kona-o-kn/document/soubor/

# Závažnost problému
2. je to vážný problém,

**Comment by psiotwo** [comment]
Fixed.
