### ISSUE TITLE
Komentáře o více znacích se nevhodně zobrazují

### ISSUE THREAD

**Issue by lindatothova** [kbss-cvut/termit-ui#114]
# Popis
**A) **Záložka komentáře u detailu pojmu****
Prosím zalomit text, aby nelezl mimo okno.
Odkaz: https://termit.fel.cvut.cz/dev/ipr/#/vocabularies/slovn%C3%ADk-z%C3%A1kona-o-katastru-nemovitost%C3%AD/terms/vklad?namespace=http://onto.fel.cvut.cz/ontologies/slovnik/
![image](https://user-images.githubusercontent.com/80691594/112051704-92b75680-8b52-11eb-93ba-8028eac31bbc.png)

 **B) Přehled **naposledy komentovaných pojmů** na hlavní straně**
V tomto přehledu navrhuji zobrazit max prvních 100 znaků komentáře a zároveň končit celým slovem (neuříznout slovo)+připojit "..." 
Celý komentář si pak uživatel zobrazí po kliknutí na odkaz pojmu - proklikem bych se měla dostat **ROVNOU na záložku komentáře** v detailu pojmu.
Odkaz: https://termit.fel.cvut.cz/dev/ipr/#/
![image](https://user-images.githubusercontent.com/80691594/112054015-59341a80-8b55-11eb-834d-99025244768c.png)

**Comment by psiotwo** [comment]
Fixed.
