### ISSUE TITLE
Nezobrazují se "přiřazené pojmy" v detailu dokumentu

### ISSUE THREAD

**Issue by lindatothova** [kbss-cvut/termit-ui#115]
# Popis problému
- pomocí anotátoru přiřazuji pojmy z dokumentu do slovníku, ale "přiřazené pojmy" se v detailu dokumentu nezobrazují 
- instance: https://termit.fel.cvut.cz/dev/ipr
- slovník: Slovník zákona o KN
- odkaz: https://termit.fel.cvut.cz/dev/ipr/#/resources/document?namespace=http://onto.fel.cvut.cz/ontologies/slovnik/slovn%C3%ADk-z%C3%A1kona-o-kn/

# Závažnost problému
3. zpomaluje mě to,

**Comment by ledsoft** [comment]
Po odebrání správy zdrojů není relevantní.
