### ISSUE TITLE
V anotátoru nelze přidat nový pojem/definici, pokud obsahuje slovo označené jako "Navrhovaný výskyt neznámého pojmu"

### ISSUE THREAD

**Issue by lindatothova** [kbss-cvut/termit-ui#116]
# Popis problému
V anotátoru nelze přidat nový pojem/definici, pokud obsahuje slovo označené jako "Navrhovaný výskyt neznámého pojmu".
Po označení textu se objeví následující okno, dále po kliknutí na kteroukoliv z možností okno jen zmizí a dál se nic neděje.

![image](https://user-images.githubusercontent.com/80691594/112060789-ea0ef400-8b5d-11eb-8b61-6a2b809c2ca9.png)

- instance: https://termit.fel.cvut.cz/dev/ipr
- slovník: Slovník zákona o KN
- odkaz: https://termit.fel.cvut.cz/dev/ipr/#/resources/zakonyprolidi_cs_2013_256_v20200701.html/annotate?namespace=http://onto.fel.cvut.cz/ontologies/slovnik/slovn%C3%ADk-z%C3%A1kona-o-kn/document/soubor/

# Závažnost problému 
2. je to vážný problém,

**Comment by psiotwo** [comment]
V anotátoru není možné vytvářet anotace nad již anotovaným fragmentem textu.

Je však možné navrhovaný výskyt pojmu odstranit (klikněte na tento výskyt a použijte ikonu pro smazání) a poté vytvořit požadovanou anotaci.

**Comment by ledsoft** [comment]
Pravděpodobná hlavní příčína viz #121

**Comment by ledsoft** [comment]
@psiotwo IMHO vyřešeno, viz #121
