### ISSUE TITLE
Záložka pojmy by měla zobrazovat počet pojmů daného slovníku

### ISSUE THREAD

**Issue by lindatothova** [kbss-cvut/termit-ui#120]
# Popis
Jako editor slovníku potřebuji znát počet pojmů ve slovníku.
Přidejte do hlavičky záložky pojmy na detailu slovníku badge s počtem pojmů v daném slovníku.

# Využití
Získám rychlý přehled o rozsahu slovníku.

# Užitečnost
2. zmíněný scénář lze bez funkce realizovat, ale zdržuje mě to

**Comment by psiotwo** [comment]
https://kbss.felk.cvut.cz/redmine/issues/1542

**Comment by psiotwo** [comment]
Rozmyslet vizualizaci s importy/bez importů
