### ISSUE TITLE
Zjednodušení práce se souvisejícími pojmy

### ISSUE THREAD

**Issue by psiotwo** [kbss-cvut/termit-ui#122]
# Popis
V současné době není možné pojmy provazovat obecnou vazbou jinak než pomocí doplňkových atributů. Ty však odkazy na pojmy (URL) nezobrazují jako odkazy a není možné se tak dostat z jednoho pojmu na druhý.

Jako **editor slovníku**
potřebuji **vidět a upravovat související pojmy**
abych mohl **modelovat obecné nehierarchické vztahy mezi pojmy**.

Současné pojmy budou mít podobu seznamu, do kterého lze přidávat nové pojmy, existující související pojmy odebírat. V editačním režimu se v seznamu rovněž zobrazí pojmy automaticky nalezené v definici daného pojmu. Editor slovníku je bude moci schválit, nebo zamítnout. Po schválení se z pojmu stane pojem související (bude nově vidět v režimu prohlížení pojmu). To, že je pojem původně navržen textovou analýzou, bude tato informace zobrazena u pojmu.

**Comment by psiotwo** [comment]
@lindatothova posílám návrh.

**Comment by lindatothova** [comment]
Režim prohlížení pojmu znamená toto okno? Děkuji:)
![image](https://user-images.githubusercontent.com/80691594/112326807-23a64300-8cb5-11eb-929e-3f246bb546f9.png)

**Comment by psiotwo** [comment]
Ano, myslel jsem to tak. Ale je možné to samozřejmě nechat na obou obrazovkách.

**Comment by lindatothova** [comment]
Doplnění - editor slovníku potřebuje přidávat související pojmy i z ostatních slovníků (pravděpodobně z "importovaných slovníků").

**Comment by lindatothova** [comment]
V detailu pojmu budeme chtít zobrazovat další pojmy v tomto pořadí
1. ekvivalentní pojmy
2. nadřazené a podřazené pojmy
3. související pojmy

**Comment by psiotwo** [comment]
Zatím implementována obecná logika práce se souvisejícími pojmy. Definičně související pojmy budou řešeny v návazném ticketu https://github.com/kbss-cvut/termit-ui/issues/164
