### ISSUE TITLE
Anotátor by měl zobrazovat slovník, který používá

### ISSUE THREAD

**Issue by psiotwo** [kbss-cvut/termit-ui#123]
# Popis
Jako **editor slovníku**
potřebuji **vidět, který slovník používá anotátor pro textovou analýzu**
abych **mohl dokončit editaci pojmů původně vytvořených v anotátoru v detailu slovníku. **

Odkaz na slovník použitý anotátorem bude klikatelný a bude vést na detail slovníku v TermIt.

**Comment by psiotwo** [comment]
@lindatothova posílám návrh.

**Comment by lindatothova** [comment]
Díky, návrh vyhovuje.
Stejný odkaz na slovník by se mohl objevit i na stránce detailu dokumentu:
https://termit.fel.cvut.cz/dev/ipr/#/resources/document?namespace=http://onto.fel.cvut.cz/ontologies/slovnik/slovnik-metropolitniho-planu/

**Comment by lindatothova** [comment]
Pardon, na stránce detailu dokumentu odkaz na slovník už je (jen jsem si ho nikdy pořádně nevšimla):

![image](https://user-images.githubusercontent.com/80691594/112335257-60296d00-8cbc-11eb-85ac-f69cd19bb485.png)

**Comment by lindatothova** [comment]
Odkaz na slovník funguje, ale je často schován legendou a není vůbec vidět.

**Možné řešení**: odkaz přesunout na levou stranu okna

**Comment by psiotwo** [comment]
Můžeme řešit v rámci https://github.com/kbss-cvut/termit-ui/issues/133 tím, že se legenda (jak obrázek ukazuje) zobrazí pod tlačítkem.

**Comment by lindatothova** [comment]
Souhlasím.
