### ISSUE TITLE
Úprava UI anotátoru

### ISSUE THREAD

**Issue by lindatothova** [kbss-cvut/termit-ui#133]
# Popis
1. **Pozadí**
Na bílém pozadí anotátoru jsou dobře vidět barevné anotace, anotovaný text je přehlednější a čitelnější. Bílé pozadí je nyní na DEV prostředí, prosíme o zachování tohoto pozadí a nasazení i do produkčního prostředí.

2. **Legenda a tlačítko Analyzovat**
Navrhujeme tuto grafickou úpravu - přehození pořadí a doplnění nadpisu Legenda:
![image](https://user-images.githubusercontent.com/80691594/113713536-c2846380-96e7-11eb-96ad-61fe8c58952b.png)

# Užitečnost
3. bylo by hezké ji mít, ale bez problémů se bez ní obejdu
****

**Comment by lindatothova** [comment]
Jako **editor slovníku**
NEpotřebuji vidět **Výskyt chybějícího pojmu** v legendě anotátoru.

Při našem nastavení aplikace nelze **Výskyt chybějícího pojmu**  ve slovníku vytvořit. Chybějící pojem by vznikl, kdyby šlo smazat pojem ze slovníku, který je anotovaný v dokumentu.

Další podobný případ je  **Navrhovaný výskyt chybějícího pojmu** v legendě anotátoru.

**Řešení:** Vypustit z legendy **Výskyt chybějícího pojmu** a **Navrhovaný výskyt chybějícího pojmu**, legenda bude přehlednější.

**Comment by psiotwo** [comment]
Smysluple stavy dle @psiotwo a @ledsoft :
- Anotace se načítá (použité i pro navrhovanou anotaci, příp. legendu odstranit)
- Anotace bez pojmu (@blcham jaký je use-case pro tento stav?)
- Výskyt existujícího pojmu
- Definice pojmu
- Definice bez pojmu (@blcham jaký je use-case pro tento stav?)
- Navrhovaný výskyt nového pojmu
- Existující výskyt nového pojmu

(Chybějící pojmy bychom v legendě nezobrazovali. Ještě k diskusi, jak tyto chyby komunikovat - další notifikace? error log? atd.)
