### ISSUE TITLE
Podpora formátování definic a doplňujících poznámek

### ISSUE THREAD

**Issue by psiotwo** [kbss-cvut/termit-ui#136]
# Popis

Jako uživatel TermItu
potřebuji mít možnost formátovat definice a doplňující poznámky. V tuto chvíli se jedná zejména o odřádkování, příp. položkové seznamy (body zákona a nařízení).

**Comment by lindatothova** [comment]
Posílám podrobnější specifikaci:

**Implementaci formátování vyžadují tyto atributy**
- "Definice" a "Doplňující poznámka" na detailu **pojmu** 
- "Popis" na detailu **slovníku**
- "Popis" na detailu **dokumentu slovníku**
</br>

**GUI Markdown editoru by mělo obsahovat** (na obrázku vyznačeno žlutě)
- editační záložku
- záložku s náhledem výsledného textu
- ikonu nadpis, tučné písmo, kurzíva, odkaz, nečíslovaný seznam, číslovaný seznam
- poznámku, že je možno použít Markdown formátování
- nevím, zda by bylo pro účely Termitu praktické dát tam nějaký default text s nápovědou (viz obr)

![image](https://user-images.githubusercontent.com/80691594/159929065-44345f59-ecde-4a10-ba7b-539d266edbd5.png)

**Comment by lindatothova** [comment]
Markdown editor vypadá dobře, testovala jsem ho a mám k tomu ještě toto:
- na horní liště **vlevo** prosím zobrazit tyto dvě ikony 
![image](https://user-images.githubusercontent.com/80691594/162888110-9c1ca8b4-a2b4-4d33-aa79-e69315ba3465.png)
- na horní liště **vpravo** potom všechny ostatní ikony
- blokové uvozovky se mi nezobrazují dobře (spíše je ale moc nevyužijeme, takže by tam nemuseli být)

**Comment by ledsoft** [comment]
@lindatothova Upraveno a nasazeno na development. Do lišty jsem místo blokové citace dal ikonu pro tabulku.

**Comment by MichalMed** [comment]
Tabulku tam nevidím, ale je to za mě ok. Hoď na prod a zavíráme.
