### ISSUE TITLE
Zobrazení dalších komentovaných pojmů na dashboardu

### ISSUE THREAD

**Issue by psiotwo** [kbss-cvut/termit-ui#153]
Jako čtenář/plný uživatel termitu,
chci mít možnost vidět i starší komentované pojmy, nejen prvních pět
abych nepřišel o komentáře, pokud jsem dlouho na dashboard nekoukal, nebo pokud příliš mnoho pojmů bylo okomentováno v nedávné minulosti.

**Comment by lindatothova** [comment]
Domluvili jsme se na řešení pomocí stránkování naposledy komentovaných pojmů - zobrazeny budou komentované pojmy za poslední 3 týdny, ale pokud jejich počet bude menší než 5, zobrazeno bude 5 naposledy komentovaných pojmů.

Highlight nově komentovaných pojmů od posledního přihlášení ještě upřesníme.

**Comment by lindatothova** [comment]
**Highlight nově komentovaných pojmů** od posledního přihlášení uživatele - budeme chtít, protože uživateli pomůže rychle identifikovat nové komentáře.

Měli bychom zájem i o **týdenní notifikaci emailem** o komentářích (nevím, jestli to už nepatří do nového ticketu - přesunuto do #304 )

- každé pondělí 9:00
- autorovi slovníku a adminovi na email, který je použit pro username
**Pozn.: až bude možno přiřadit editora/editory ke každému slovníku zvášť - bude tato notifikace posílána JEN EDITOROVI SLOVNÍKU**
- bude obsahovat výpis pojmů, u kterých v daném týdnu nastala změna (vytvoření/úprava/odstranění) v komentářích + zobrazení těchto komentářů s údaji níže:
**Pozn.: až bude možno přiřadit editora/editory ke každému slovníku zvášť - notifikace bude obsahovat výpis pojmů JEN ZE SLOVNÍKŮ EDITORA, u kterých v daném týdnu nastala změna**

_vytvoření/úprava/odstranění, autor komentáře, datum vytvoření/úpravy/odstranění
text komentáře_
