### ISSUE TITLE
Služba vyhledávání napříč všemi slovníky

### ISSUE THREAD

**Issue by lindatothova** [kbss-cvut/termit-ui#156]
# Popis
Pro prohlížecí aplikaci slovníků (vzniká na IPR)
potřebujeme veřejnou službu, která bude umět „full text“ vyhledávání napříč všemi slovníky.

# Bližší specifikace
Vstupní parametry:
vocabuleries: []
- seznam slovníků napříč kterými bude hledáno.
- Není-li specifikován, hledá napříč všemi slovníky v TermItu

Odpověď:
-	Mohla by vypadat nějak takto.
![image](https://user-images.githubusercontent.com/80691594/117945634-cde23480-b30e-11eb-8d53-0b6192a85d4e.png)

# Užitečnost
1. zmíněný scénář bez navrhované funkce realizovat nelze

**Comment by psiotwo** [comment]
Zatím je k dispozici full-text napříč všemi slovníky (vrací ovšem nejen pojmy ale i slovníky a neumí filtrovat podle jednotlivých slovníků), viz
https://termit.fel.cvut.cz/service/ipr/termit/rest/search/fts?searchString=%C5%A1acht

Takže zatím je možné filtrovat podle slovníků na klientské straně. Pokud by to byl výkonností problém, určitě není problém umožnit filtrování podle slovníků na serveru.
