### ISSUE TITLE
Import/export slovníku

### ISSUE THREAD

**Issue by psiotwo** [kbss-cvut/termit-ui#165]
# Popis
Jako editor slovníku
chcí mít možnost slovník importovat/exportovat
abych si mohl udělat zálohu, příp. využít slovník v jiném nástroji. 

Cílem je udělat export všech SKOS částí slovníku a umožnit jejich import do existujícího slovníku (tak, že nahradí všechny pojmy v daném slovníku).

**Comment by blcham** [comment]
+1
