### ISSUE TITLE
Nápověda pro anotátor

### ISSUE THREAD

**Issue by lindatothova** [kbss-cvut/termit-ui#170]
# Popis
Jako editor slovníku, který poprvé používá anotátor,
potřebuji použít nápovědu v anotátoru,
která mě navede, jak s anotátorem pracovat, a podrobněji mi vysvětlí pojmy v legendě.

# Možné řešení
Využít tooltip nápovědy, jak je naznačeno symbolem otazníku na obrázku. Pod větším (hlavním) otazníkem nahoře by se mohla skrývat "hlavní" nápověda - něco ve smyslu začněte označením textu v dokumentu...

![image](https://user-images.githubusercontent.com/80691594/120383690-7b040780-c325-11eb-82b8-a1a2ab895dc6.png)

# Užitečnost
Popište, jak užitečná Vám funkce přijde
3. bylo by hezké ji mít, ale bez problémů se bez ní obejdu

**Comment by psiotwo** [comment]
@MichalMed - mělo by být součástí https://github.com/kbss-cvut/termit-ui/issues/170

**Comment by MichalMed** [comment]
https://kbss-cvut.github.io/termit-web/cs/tutorial#anotace-dokument%C5%AF

**Comment by psiotwo** [comment]
Implementováno jako odkaz z legendy na tutoriál, který je na webu - v anglické a české verzi.
