### ISSUE TITLE
Drop-down list pro výběr related/exact pojmů - zobrazení pojmu spolu se slovníkem, ze kterého pojem pochází

### ISSUE THREAD

**Issue by lindatothova** [kbss-cvut/termit-ui#176]
# Popis
Jako editor slovníku
potřebuji vybrat related/exact pojem ze seznamu, kde je název pojmu zobrazen spolu s názvem zdrojového slovníku
(při editaci detailu pojmu).

Grafické řešení - podobně jako v KODI.

# Využití
Při shodných názvech pojmů u více slovníků mohu identifikovat a vybrat správný related/exact pojem.

# Užitečnost
1. zmíněný scénář bez navrhované funkce realizovat nelze

**Comment by ledsoft** [comment]
https://kbss.felk.cvut.cz/redmine/issues/1589

**Comment by psiotwo** [comment]
příklad https://termit.fel.cvut.cz/dev/ipr/#/vocabularies/psp-2016/terms/nezastaviteln%C3%A9-%C3%BAzem%C3%AD?namespace=https://slovn%C3%ADk.gov.cz/datov%C3%BD/&includeImported=true

**Comment by lindatothova** [comment]
Grafické zobrazení se mi líbí. Mám otázku ke tvorbě řetězce označujícího název cizího slovníku (např. D-SGOV-PSP-2016) - skládá se automaticky z tohoto atributu https://slovník.gov.cz/datový/psp-2016 ?

**Comment by psiotwo** [comment]
Ano, jedna se o zkratku IRI slovniku. Aktualne se pro zobrazeni zkratky slovniku pouziva stejna knihovna/logika jako ve Vyrobni lince na KODI.

Logiku je mozne vysledovat pro jednotlive typy slovniku v:
https://github.com/opendata-mvcr/assembly-line-shared/blob/main/src/vocabulary-utils/vocabularyTypes.json

**Comment by lindatothova** [comment]
Díky, knihovna zkratek z KODI je pro nás zatím dostačující.

Otestovala jsem to na všech typech pojmů (related, exact, hierarchické), funguje to dobře a hodně to pomohlo orientaci mezi pojmy z cizích slovníků.
