### ISSUE TITLE
Doplnujici poznamka pri vytvareni pojmu se propisuje do vice jazyku

### ISSUE THREAD

**Issue by psiotwo** [kbss-cvut/termit-ui#178]
# Popis problému
Popište:
- při vytváření pojmu se doplňující poznámka propíše do všech jazyků, které při přidávání pojmů uživatel zvolí.

# Závažnost problému
3. zpomaluje mě to,

**Comment by psiotwo** [comment]
https://kbss.felk.cvut.cz/redmine/issues/1599

**Comment by lindatothova** [comment]
Otestováno - v pořádku
