### ISSUE TITLE
Špatný překlad content typů

### ISSUE THREAD

**Issue by MichalMed** [kbss-cvut/termit-ui#183]
# Popis
v roletě typ je "intrinsic trope", ale kontrola úplnosti pojmu uvádí "aspect"

# Užitečnost
3. bylo by hezké ji mít, ale mate to uživatele
****

**Comment by MichalMed** [comment]
stejný případ i u "relator" a "relation"

**Comment by psiotwo** [comment]
Toto by mělo být opraveno na straně TermIta - ustálená UFO terminologie dnes využívá spíš Relation/Aspect.

**Comment by MichalMed** [comment]
testoval jsem na https://termit.fel.cvut.cz/dev/ipr/#/vocabularies/klasifikace-stavebn%C3%ADch-d%C4%9Bl/terms/testovac%C3%AD-term-pro-smaz%C3%A1n%C3%AD?namespace=https://slovn%C3%ADk.gov.cz/generick%C3%BD/ a není opraveno

**Comment by ledsoft** [comment]
Ještě není nasazeno na odkazované instanci.

**Comment by ledsoft** [comment]
Nasazeno na KBSS dev i IPR dev

**Comment by MichalMed** [comment]
Super, funguje
