### ISSUE TITLE
I když je deploy v angličtině, vyžaduje definice v češtině

### ISSUE THREAD

**Issue by MichalMed** [kbss-cvut/termit-ui#184]
# Popis problému
problém je vidět v live-demu termitu. Pokud mám nastaven jako hlavní jazyk angličtinu, validátor úplnosti pojmů stejně vyžaduje definici v češtině.

# Závažnost problému
- popište, jak závažný pro práci s TermItem pro Vás problém je:
1. je to závažný problém pro expanzi mimo ČR a pro tutoriál

**Comment by ledsoft** [comment]
Fixed, @MichalMed please verify on the demo instance.

**Comment by ledsoft** [comment]
@MichalMed ping

**Comment by MichalMed** [comment]
Verified. Funny thing - length of definition is checked for every language.
