### ISSUE TITLE
Nefunkční vyhledávač

### ISSUE THREAD

**Issue by MichalMed** [kbss-cvut/termit-ui#189]
# Popis problému

Na nasazení IPR nefunguje vyhledávání
![Screenshot from 2021-08-18 13-37-36](https://user-images.githubusercontent.com/3779672/129891842-d8831c20-3f1d-4017-947f-5dc68f2690fc.png)
Nefunguje ani v devu, ani v produkci.

# Závažnost problému
2. je to vážný problém,

**Comment by psiotwo** [comment]
Fixed - missing lucene connectors.
