### ISSUE TITLE
Vyhledávací služba ve slovnících DTM

### ISSUE THREAD

**Issue by lindatothova** [kbss-cvut/termit-ui#192]
Pro prohlížecí aplikaci slovníků DTM
potřebujeme veřejnou službu, která bude umět vyhledávat pojmy ve dvou slovnících DTM - ve **Slovníku reálných objektů DTM **a ve** Slovníku datového modelu DTM**.

# Využití
V prohlížecí aplikaci bude možné vyhledávat dle názvu pojmu.

# Užitečnost
1. zmíněný scénář bez navrhované funkce realizovat nelze

**Comment by ledsoft** [comment]
IMHO subset #156 , kde by jako parametr byly identifikátory zmíněných slovníků.

**Comment by psiotwo** [comment]
Example call is :

{{TERMIT_SERVER}}/rest/search/fts/terms?searchString=DTM&vocabulary=https://slovník.gov.cz/legislativní/sbírka/2000/1994&vocabulary=https://slovník.gov.cz/generický/struktura-jvf-dtm
