### ISSUE TITLE
Export slovníku i s propojeními do ostatních slovníků

### ISSUE THREAD

**Issue by psiotwo** [kbss-cvut/termit-ui#194]
# Popis
Cílem je umožnit export slovníku spolu s ostatními slovníky, které tranzitivně referencují (pojem se stejným významem, související pojem, nadřazený pojem) daný nějaký pojem z daného slovníku.

# Využití
Pro získání aktuální verze všech slovníků DTM .

**Comment by psiotwo** [comment]
Upřesnění - bude se jednat pouze o pojmy pocházející ze stejného slovníku a pojmy, které jsou propojeny pomocí vazby skos:exactMatch.

**Comment by lindatothova** [comment]
Ano, takto to dává smysl, protože skos:exactMatch je, myslím, jediná tranzitivní reference v našich slovnících (resp. DTM slovnících).
