### ISSUE TITLE
Export do XLS obsahuje chybnou hodnotu pole related

### ISSUE THREAD

**Issue by psiotwo** [kbss-cvut/termit-ui#195]
# Popis problému
Je-li A relatedMatch B, potom se v XLS exportu u pojmu A objeví pojem B jak ve sloupci "Related Match Terms", tak ve sloupci "Related Terms" . Pojem B by se ale měl objevit pouze v "Related Match Terms" .

Viz
https://termit.fel.cvut.cz/dev/ipr/#/vocabularies/slovn%C3%ADk-re%C3%A1ln%C3%BDch-objekt%C5%AF-dtm?namespace=https://slovn%C3%ADk.gov.cz/generick%C3%BD/

**Comment by ledsoft** [comment]
Je to způsobeno tím, že `relatedMatch subPropertyOf related`, takže `A relatedMatch B` implikuje i `A related B`. V atributu `Term.inverseRelated` tedy jsou i vyinferované hodnoty na základě `relatedMatch`.

**Comment by ledsoft** [comment]
@psiotwo Není to v projektu, ale jinak oprava hotova a nasazeno.
