### ISSUE TITLE
Ve veřejném rozhraní nelze zobrazit detail pojmu

### ISSUE THREAD

**Issue by psiotwo** [kbss-cvut/termit-ui#211]
# Popis problému
- Otevřu přihlašovací stránku TermItu
- zobrazím detail slovníku
- chci zobrazit detail pojmu, ale přesměruje mě to hned na přihlášení

Z logu je vidět, že request `GET https://termit.fel.cvut.cz/service/ipr/termit/rest/vocabularies/bim-komponenty-0/terms/G/def-related-target?namespace=http%3A%2F%2Fslovn%C3%ADk.gov.cz%2Fgenerick%C3%BD%2F` vrací 401

# Závažnost problému
1. nemohu vůbec pracovat,

**Comment by psiotwo** [comment]
Hotfix - zobrazeni detailu - ovsem za cenu, ze ve verejnem view nejsou videt related pojmy.

**Comment by lindatothova** [comment]
Na dev otestováno, možno nasadit na produkci.

**Comment by ledsoft** [comment]
Nasazeno na produkci.
