### ISSUE TITLE
Problém s editací pojmu.

### ISSUE THREAD

**Issue by psiotwo** [kbss-cvut/termit-ui#212]
# Popis problému
k tomuto pojmu na dev přidána definice a smazána doplňující poznámka https://termit.fel.cvut.cz/dev/ipr/#/vocabularies/2020-new/terms/vlastnosti-a-dal%C5%A1%C3[…]egislativn%C3%AD/sb%C3%ADrka/393/&includeImported=false (edited) 

u pojmu se stejným významem https://termit.fel.cvut.cz/dev/ipr/#/vocabularies/dtm/terms/vlastnosti-a-dal%C5%A1%C3%AD-v[…]/slovn%C3%ADk.gov.cz/datov%C3%BD/&includeImported=false chci opravit definici a smazat poznámku a hlásí mi to chybu

Změna ale neproběhne, definice je nezměněná (přidala jsem nějaké slovo) a poznámka není smazaná.

Následně se poznámku podařilo smazat, chybu mi to hlásí při editaci textu definice - a neprovede se

**Comment by ledsoft** [comment]
Bylo způsobeno:
1. Chybějícími language tagy po importu dat
2.  neschopností TermIta taková data zobrazit a znovu uložit bez přiřazení nevalidního language tagu "@@none".

Pro 1. vytvořen ticket v Redmine, 2. opravena https://github.com/kbss-cvut/termit/pull/118, navrhuji tedy zavřít.

**Comment by lindatothova** [comment]
Děkujeme za opravu. Požádám ještě Markétu o otestování a potom ticket zavřu.

**Comment by ledsoft** [comment]
Pozor, oprava bude dle @psiotwo nasazena až během odpoledne/večera

**Comment by lindatothova** [comment]
Díky, počítáme s tím.

**Comment by psiotwo** [comment]
Reportovaný problém samotný lze testovat i teď, protože ten závisel jen na datech, která už byla opravená a není třeba nové nasazení.

Po nasazení, které za chvíli udělám, bude možné otestovat i bod 2 (importnout slovnik bez language tagu a pak editovat pojem), který píše Martin, pokud bys chtěla.

**Comment by psiotwo** [comment]
Je to nasazeno.
