### ISSUE TITLE
Import není opakovatelný

### ISSUE THREAD

**Issue by psiotwo** [kbss-cvut/termit-ui#214]
Export a následná obnova slovníku ze zálohy se napodruhé nepodaří (s červenou hláškou)

Je třeba sem doplnit detaily.

**Comment by ledsoft** [comment]
Zdá se, že problémem je, že SKOS export exportuje glosář včetně jeho původní IRI, která není kompatibilní s IRI, kterou požaduje import.
Např., export slovníku s IRI `http://onto.fel.cvut.cz/ontologies/slovnik/ml-test` s glosářem s IRI `http://onto.fel.cvut.cz/ontologies/slovník/agendový/popis-dat/pojem/glosar/instance-2049395067` vyexportuje glosář (`skos:ConceptScheme`) se zmiňovanou IRI. Ale import očekává, že vstupní TTL bude obsahovat glosář s IRI `http://onto.fel.cvut.cz/ontologies/slovnik/ml-test/glosář`.

Resp. problém asi je, že defaultní IRI glosáře je generována automaticky z JOPA a má podobu `http://onto.fel.cvut.cz/ontologies/slovník/agendový/popis-dat/pojem/glosar/instance-${randomInt}` namísto očekávaného vzoru `${iri-slovníku}/glosář`.

**Comment by ledsoft** [comment]
Další (nejspíš hlavní) problém je v tom, že import kontroluje, jestli glosář již neexistuje a pokud ano, hodí výjimku. To ale IMHO nedává smysl v případě, že znovu nahrávám existující slovník (což importer dle dalšího kódu a způsobu použití také podporuje).

**Comment by ledsoft** [comment]
Fixed in [2.11.3](https://github.com/kbss-cvut/termit/releases/tag/v2.11.3).
