### ISSUE TITLE
Import má selhat když stringy nemají language tag

### ISSUE THREAD

**Issue by psiotwo** [kbss-cvut/termit-ui#217]
Kdyz prefLabel nejakeho pojmu nema language tag, import selze. Je treba 
1) spravne chybu osetrit a informovat uzivatele.
2) zakazat import definic/poznámek/alternativních labelů/vyhledávacích labelů bez language tagu.

**Comment by psiotwo** [comment]
@lindatothova nyní by nemělo být možné importovat data bez language tagu. Testuj prosím na novém slovníku, ať se do toho nemotají případné chyby importu.

**Comment by lindatothova** [comment]
Otestováno, je to v pořádku. Děkuji.
