### ISSUE TITLE
Chybí badge s názvem slovníku u některých exactMatch pojmů

### ISSUE THREAD

**Issue by lindatothova** [kbss-cvut/termit-ui#218]
# Popis problému
U některých exactMatch pojmů se neobrazuje badge s názvem slovníku, do kterého exactMatch pojem patří.
Např.: https://termit.fel.cvut.cz/ipr/#/vocabularies/dtm/terms/dopravn%C3%AD-ostr%C5%AFvek?namespace=https://slovn%C3%ADk.gov.cz/datov%C3%BD/
![image](https://user-images.githubusercontent.com/80691594/149306667-72afd558-b23c-47c9-842c-5a557eb6bf96.png)

# Závažnost problému
3. zpomaluje mě to,

**Comment by lindatothova** [comment]
Na dev otestováno, možno nasadit na produkci.

**Comment by ledsoft** [comment]
Nasazeno na produkci.
