### ISSUE TITLE
Pojem, který vznikl anotováním dokumentu, nelze ze slovníku smazat

### ISSUE THREAD

**Issue by lindatothova** [kbss-cvut/termit-ui#221]
# Popis problému
Pojem **bezpečnostní pásmo plynových zařízení**
https://termit.fel.cvut.cz/ipr/#/vocabularies/slovn%C3%ADk-z%C3%A1kona-%C4%8D.-458-2000-sb.-o-podm%C3%ADnk%C3%A1ch-podnik%C3%A1n%C3%AD-a-o-v%C3%BDkonu-st%C3%A1tn%C3%AD-spr%C3%A1vy-v-energetick%C3%BDch-odv%C4%9Btv%C3%ADch/terms/bezpe%C4%8Dnostn%C3%AD-p%C3%A1smo-plynov%C3%BDch-za%C5%99%C3%ADzen%C3%AD?namespace=https://slovn%C3%ADk.gov.cz/generick%C3%BD/&includeImported=false
který byl vytvořen anotováním dokumentu https://termit.fel.cvut.cz/ipr/#/resources/document/files/zakon_c458_2000sb_energeticky_zakon.html?namespace=https://slovn%C3%ADk.gov.cz/generick%C3%BD/slovn%C3%ADk-z%C3%A1kona-%C4%8D.-458-2000-sb.-o-podm%C3%ADnk%C3%A1ch-podnik%C3%A1n%C3%AD-a-o-v%C3%BDkonu-st%C3%A1tn%C3%AD-spr%C3%A1vy-v-energetick%C3%BDch-odv%C4%9Btv%C3%ADch/&fileNamespace=https://slovn%C3%ADk.gov.cz/generick%C3%BD/slovn%C3%ADk-z%C3%A1kona-%C4%8D.-458-2000-sb.-o-podm%C3%ADnk%C3%A1ch-podnik%C3%A1n%C3%AD-a-o-v%C3%BDkonu-st%C3%A1tn%C3%AD-spr%C3%A1vy-v-energetick%C3%BDch-odv%C4%9Btv%C3%ADch/document/soubor/
nelze ze slovníku **Slovník zákona č. 458/2000 Sb., o podmínkách podnikání a o výkonu státní správy v energetických odvětvích**
smazat a to ani po odstranění výskytu pojmu v anotátoru.

Dle zobrazení odkazu "Zobrazit v dokumetru" tam ty anotace (v tomto případě anotace definice) stále někde visí:
![image](https://user-images.githubusercontent.com/80691594/150410747-62a6a4e2-304f-4b02-9f67-b30f98de1bd8.png)
Po kliknutí na "Zobrazit v dokumetru" se zobrazí:
![image](https://user-images.githubusercontent.com/80691594/150411170-5bc097ae-a7ed-47db-a50d-be12ad2f0629.png)

Pokus o smazání pojmu končí touto hláškou (tlačítko "Odstranit" na detailu pojmu nebo v editačního módu pojmu):
![image](https://user-images.githubusercontent.com/80691594/150409428-7dc0e558-c813-4638-aca6-c09524b792f8.png)

# Závažnost problému
2. je to vážný problém

**Comment by ledsoft** [comment]
Nasazeno na produkci.
