### ISSUE TITLE
Služba pro ukládání komentářů do Termitu

### ISSUE THREAD

**Issue by lindatothova** [kbss-cvut/termit-ui#226]
# Popis
Pro prohlížecí aplikaci slovníku DTM
(https://app.iprpraha.cz/apl/app/prohlizecka_slovniku?slovnik=slovnik2&pojem=dopravn%C3%AD-ostr%C5%AFvek)
potřebujeme veřejnou REST službu, která bude umět ukládat komentáře do Termitu (komentáře budou v prohlížečce vytvářeny nové, příp. bude možnost je editovat).

# Využití
V prohlížečce slovníku bude možné komentovat pojmy a takto vzniklé nové komentáře se zobrazí i u odpovídajícího pojmu v Termitu (příp. se zobrazí editovaný komentář, pokud bude v prohlížečce upraven).

# Užitečnost
1. zmíněný scénář bez navrhované funkce realizovat nelze 
****

**Comment by ledsoft** [comment]
Na základě diskusí (převážně na Slacku) bude vyřešeno s využitím stávající funkcionality TermItu. Pro referenci popsáno níže.

1. Komentáře bude moci přidávat pouze uživatelé registrovaní v TermItu (z důvodu zamezení spamu).
2. Prohlížečka DTM pro přidání komentáře požádá uživatele o přihlášení pomocí přihlašovacích údajů TermItu. Interně využije [přihlašovací endpoint TermItu](https://app.swaggerhub.com/apis/ledvima1/TermIt/2.8.0-IPR#/default/post_j_spring_security_check), který vrací JWT.
3. Prohlížečka použije poskytnutý přihlašovací token při volání [API pro vytvoření komentáře](https://app.swaggerhub.com/apis/ledvima1/TermIt/2.8.0-IPR#/default/post_rest_terms__normalizedName__comments) na základě textu zadaného uživatelem.

Další související API, které lze využít:
- [API pro získání komentářů k pojmu](https://app.swaggerhub.com/apis/ledvima1/TermIt/2.8.0-IPR#/default/get_rest_terms__normalizedName__comments)
- [API pro editaci existujícího komentáře](https://app.swaggerhub.com/apis/ledvima1/TermIt/2.8.0-IPR#/default/put_rest_comments__idFragment_)
- [API pro smazání vlastního komentáře](https://app.swaggerhub.com/apis/ledvima1/TermIt/2.8.0-IPR#/default/delete_rest_comments__idFragment_)
- [API pro reakci na existující komentář](https://app.swaggerhub.com/apis/ledvima1/TermIt/2.8.0-IPR#/default/post_rest_comments__idFragment__reactions)
