### ISSUE TITLE
TermIt nevyhledává podle synonym

### ISSUE THREAD

**Issue by MichalMed** [kbss-cvut/termit-ui#227]
Pokud je to možné, pokuste se informaci o chybě rozepsat dle následující struktury, pomůžete nám ji rychleji identifikovat a opravit.

# Popis problému
Pojem https://termit.fel.cvut.cz/ipr/#/vocabularies/slovn%C3%ADk-pro-bim/terms/datov%C3%BD-standard-staveb?namespace=https://slovn%C3%ADk.gov.cz/generick%C3%BD/ má jako synonymum nastaveno "DSS", ale nejde podle něj vyhledat.

# Závažnost problému
4. příliš mojí práci neovlivňuje.

# Alternativy řešení
Nejsem si jistý, jestli to tak není správně, a vyhledávání nemá probíhat pouze podle "Vyhledávacích textů"?

**Comment by MichalMed** [comment]
@ledsoft mohl bys prosím jen potvrdit/vyvrátit, jestli se to takhle má nebo nemá chovat?

**Comment by ledsoft** [comment]
Souvisí nejspíš s https://kbss.felk.cvut.cz/redmine/issues/1346. Ačkoliv najít by to mělo, tj. chovat se to takhle nemá.

**Comment by ledsoft** [comment]
Problém je v konfiguraci deploymentu. V repozitáři chybí SKOS ontologie, takže GraphDB neví, že skos:altLabel je subPropertyOf rdfs:label.
Ontologii tam nahraju a zajistím, aby se při vytváření dalších deploymentů nemohlo stát to samé. Pak ticket zavřu.

**Comment by ledsoft** [comment]
@psiotwo

**Comment by ledsoft** [comment]
FYI, SKOS ontologii jsem do IPR repozitářů nahrál, takže FTS přes altLabel a hiddenLabel již funguje. Ještě dořešíme přidání do inicializačních dat.

**Comment by psiotwo** [comment]
Docker build & instrukce upraveny - po zamergování https://github.com/kbss-cvut/termit-docker/pull/3 je možné tento ticket zavřít.
