### ISSUE TITLE
Selhání spuštění analýzy při vytvoření pojmu

### ISSUE THREAD

**Issue by MichalMed** [kbss-cvut/termit-ui#237]
# Popis problému
Při vytváření nového pojmu vyplním název a kliknu na tlačítko vytvořit. Termit se tváří, jako že se nic nestalo a vyhodí červenou hlášku "Invocation Analysis Failed". Při zobrazení seznamu pojmů je ale vidět, že se pojem vytvořil.

# Závažnost problému
- popište, jak závažný pro práci s TermItem pro Vás problém je:

3. zpomaluje mě to

**Comment by marketaadamcova** [comment]
```
message: "Text analysis invocation failed.",…}
message: "Text analysis invocation failed."
requestUri: "/termit-server-msmt/rest/resources/mark%C3%A9ta---dp-1.txt-4.html/text-analysis"
```

**Comment by ledsoft** [comment]
O kterou instanci TermItu se jedná, prosím? Ve výpisu výše vidím `termit-server-msmt`, jedná se tedy o MSMT instanci?

**Comment by ledsoft** [comment]
Nevermind, už jsem to našel, je to MŠMT instance.

**Comment by ledsoft** [comment]
@marketaadamcova Mělo by být opraveno, prosím vyzkoušejte.

**Comment by ovitovec** [comment]
Stejný problém jsem měl i v instanci https://kbss.felk.cvut.cz/termit-csat/#/. Teď jsem zkusil přidat pojem a vše OK. Tak snad vyřešeno i v této instanci

**Comment by marketaadamcova** [comment]
za mne se zdá být vše OK
