### ISSUE TITLE
Nefunguje tlačítko otevřít v novém okně v seznamu komponent

### ISSUE THREAD

**Issue by ovitovec** [kbss-cvut/termit-ui#239]
Pokud si otevřu seznam komponent, tak když na pojem najedu myší, tak se u pojmu objeví ikonka, skrze kterou by se mi měla daná komponenta otevřít v dalším okně. Další okno to sice otevře, ale nicméně to vyhazuje hlášku Error 404. Pokud na komponentu kliknu pravým a zvolím otevřít v novém okně, pak funguje dobře.
https://kbss.felk.cvut.cz/termit-csat/#/vocabularies/slovnik-komponent-a-zavad---novy/terms/component?namespace=http://onto.fel.cvut.cz/ontologies/slovnik/&includeImported=false
https://kbss.felk.cvut.cz/termit-csat/#/ 

3. zpomaluje mě to,

**Comment by ovitovec** [comment]
TERMIT také neoznačí pojem, který není oddělen z obou stran mezerou - tedy, pokud je překlep, pomlčka, tečka, slovo bez mezery apod., tak to z pravidla pojem neoznačí. Např.: "worklight assy-the parts was found missing"
 - "worklight assy" je ve vyhledávacích pojmech, ale nebylo označeno.

**Comment by ovitovec** [comment]
Pojí se s předchozím bodem, kdy jde slova s pomlčkou uvnitř - např. cover-end, retainer-clip, spring-assy - i pokud jsou tato slova> přiřazena jako vyhledávací text, tak ho analýza neodhalí

**Comment by ledsoft** [comment]
Zmíněná ikonka umožňuje použít identifikátor pojmu jako URL (externí link), což může vést na Linked Data endpoint, který poskytuje dodatečné informace o pojmu (viz např. http://onto.fel.cvut.cz/ontologies/slovník/datový/mpp-3.5-np/pojem/krajina). Vaše instance Linked Data export zjevně zapnutý nemá (@blcham ), takže identifikátor pojmu (komponenty) nevede na existující stránku.
Když kliknete přímo na název pojmu, otevíráte jeho detail v TermItu (interní link). Viz screenshot níže.

![image](https://user-images.githubusercontent.com/2676156/155731771-e2d8c7a9-37a4-4b1f-9d54-c75076b09a77.png)
