### ISSUE TITLE
Nefunguje Docker image build

### ISSUE THREAD

**Issue by Sidonivs** [kbss-cvut/termit-ui#242]
# Popis problému
Postupuji dle návodu zde: https://github.com/kbss-cvut/termit-ui#dockerization pro build Docker image.
Na obrázku je log errorů na kterých build spuštěný příkazem `docker build -t termit .` spadne.

![image](https://user-images.githubusercontent.com/41227844/156042517-4f5a32ac-5ab8-40c8-ac4e-17c4756b1c98.png)

# Závažnost problému
1. nemohu vůbec pracovat,

**Comment by ledsoft** [comment]
Nemáte celý build log? Zrovna jsem otestoval verzi z masteru a Docker build bez problémů proběhne. Běží build na Windows nebo Linuxu?

**Comment by ledsoft** [comment]
Ok, zdá se, že jde o problém s konci řádků. Pracuji na řešení.

**Comment by Sidonivs** [comment]
Děkuji. Přikládám celý log 

[termit-ui_build.log](https://github.com/kbss-cvut/termit-ui/files/8163761/termit-ui_build.log)

Build běží na Windows.
K logu npm (zmíněném na konci) nevím jak přistoupit (cesta `/root/.npm/_logs/...-debug.log` není u mě, ale někde v Docker containeru).

**Comment by Sidonivs** [comment]
Teď jsem ještě vyzkoušel novou branch [bug/242-platform-independent-formatting](https://github.com/kbss-cvut/termit-ui/compare/bug/242-platform-independent-formatting)
![image](https://user-images.githubusercontent.com/41227844/156226469-2e72d23c-e9a0-4f0f-8822-590a9e457aa8.png)

Aktuální log zde: [termit-ui_build.log](https://github.com/kbss-cvut/termit-ui/files/8163891/termit-ui_build.log)

**Comment by ledsoft** [comment]
@Sidonivs Vyzkoušejte, prosím, přiložené PR. Odstraňuje Prettier check z Docker buildu, takže to už nebude problém (stejně tam nedával smysl). Ale změnil jsem i konfiguraci Gitu tak, aby i na Windows používal LF jako konec řádku, tak Prettier check by měl již procházet i na Windows (testováno na Win 11).
Navíc jsem přidal pre-commit hook, který provede formátování automaticky.

**Comment by Sidonivs** [comment]
@ledsoft Vyzkoušeno na Windows 10, build prochází bez problémů, za mě vyřešeno, ještě jednou děkuji.
