### ISSUE TITLE
Zobrazení atributu "Stav pojmu” na detailu pojmu

### ISSUE THREAD

**Issue by lindatothova** [kbss-cvut/termit-ui#253]
# Popis
Atribut "Stav pojmu” se zobrazuje pouze v editačním módu pojmu, potřebujeme ho zobrazit také na kartě pojmu mezi hlavními atributy.

# Užitečnost
1. zmíněný scénář bez navrhované funkce realizovat nelze 
****

**Comment by lindatothova** [comment]
Řešení by mohlo být shodné s implementací ve výrobní lince v Termitu:
- "Stav pojmu” lze editovat rovnou z detailu pojmu (zároveň lze editovat i v editačním módu)
- pokud je "Stav pojmu” nastaven na "Schválený", potom tlačítko "Upravit" na detailu pojmu je neaktivní

![image](https://user-images.githubusercontent.com/80691594/162008420-f14b76d1-5bfa-4b6a-8cae-d18182f22770.png)

**Comment by MichalMed** [comment]
navrhuji úpravu - stav pojmu by se takto (tzn. s šoupátkem) zobrazoval pouze pro editora (i teď se v editačním módu zobrazuje pouze editorovi), reader by ho viděl pouze jako label, tzn. bez možnosti přepnout. Je to tak lepší, @lindatothova ?

**Comment by lindatothova** [comment]
Souhlasím (na čtenáře jsem zapomněla)

**Comment by MichalMed** [comment]
@lindatothova běží to na devu, zkontroluj a hodíme na prod (zkus si to pod více uživateli, čtenáře máme například blueuser s heslem modrá)

**Comment by lindatothova** [comment]
Otestováno, funguje dobře, může na prod, díky.
