### ISSUE TITLE
Aktualizace definice a poznámky "Slovníku objektů ZPS Georeal"

### ISSUE THREAD

**Issue by lindatothova** [kbss-cvut/termit-ui#257]
@MichalMed Prosím o import formátované definice a poznámky do slovníku
https://termit.fel.cvut.cz/ipr/#/vocabularies/slovn%C3%ADk-objekt%C5%AF-zps-georeal?namespace=http://slovn%C3%ADk.gov.cz/generick%C3%BD/
(aktualizace skos:definition, skos:scopeNote)

Ze zdrojového html textu potřebujeme převést jen toto:

- bloky textu (tagy p, br, div)
- seznamy (tagy li, ol, ul)
- tučné písmo (b)
- kurzíva (i)
- horní index (sup)

**Comment by MichalMed** [comment]
Udělal jsem skript na triplifikaci excelu s převodem HTML znaků do markdown. Je to nasazeno na devu, prosím o kontrolu.
