### ISSUE TITLE
nelze se přihlásit

### ISSUE THREAD

**Issue by marketaadamcova** [kbss-cvut/termit-ui#263]
# Popis problému
Popište:
- po kliknutí na tlačítko přihlásit se vyskočí hláška 'přihlášení se nazdařilo'
-csat

1. nemohu vůbec pracovat,

**Comment by ledsoft** [comment]
Problém s certifikátem databázového serveru, přesměrováno na @blcham .

**Comment by ledsoft** [comment]
Vyřešeno úpravou adresy databázového serveru a systému bez zásahu @blcham .

**Comment by blcham** [comment]
@ledsoft thanks
