### ISSUE TITLE
Nefunguje export slovníku DTM do Excelu

### ISSUE THREAD

**Issue by lindatothova** [kbss-cvut/termit-ui#264]
Nelze exportovat slovník DTM do Excelu a CSV (Turtle funguje):
https://termit.fel.cvut.cz/ipr/#/vocabularies/dtm?namespace=https://slovn%C3%ADk.gov.cz/datov%C3%BD/

Excel export jiného slovníku funguje.

# Závažnost problému
1. nemohu vůbec pracovat

**Comment by lindatothova** [comment]
Na DEV mám otestováno - po kliknutí na "Exportovat - Excel" se točítko chvíli točí, potom se neděje nic, ale nakonec se DTM slovník vyexportuje (trvá to 52 s). To, že se točítko netočí po celou dobu exportu, je trochu zavádějící. Vzhledem k tomu, že slovník DTM exportuji do excelu většinou jen já, tak to takto klidně nechme. Ostatní slovníky se exportují rychle.

**Comment by ledsoft** [comment]
Ještě jsem opravil to točítko. Rychlost exportu by se dala určitě taky zoptimalizovat, je-li to problematické (DTM je dost velký slovník, tak tam je to nejvíc znát).

**Comment by lindatothova** [comment]
Díky, točítko už funguje dobře. Rychlost exportu je dostačující (DTM slovník je velký a nyní se exportuje kolem 30 s).
