### ISSUE TITLE
nefunguje označování pojmů v textu 

### ISSUE THREAD

**Issue by marketaadamcova** [kbss-cvut/termit-ui#267]
Pokud je to možné, pokuste se informaci o chybě rozepsat dle následující struktury, pomůžete nám ji rychleji identifikovat a opravit.

# Popis problému
Popište:
-po označení požadovaného pojmu v textu a zvolení pojmu vyskočí červený panel s chybovou hláškou (bez textu). Pojem se tváří jako označený, po novém otevření souboru ale pojem není označení 
- csat
- slovník komponent a závad - Markéta DP
- {timestamp: 1650545758163, status: 500, error: "Internal Server Error",…}
error: "Internal Server Error"
path: "/termit-server-csat/rest/resources/dataset1_filtered.html/content"
status: 500
timestamp: 1650545758163

1. nemohu vůbec pracovat

**Comment by ledsoft** [comment]
Opět problém s místem na disku. Annotace zřejmě generuje hromadu dočasných souborů, které po sobě neuklidí a tím se zaplní disk.

@marketaadamcova Můžu se zeptat, jakým způsobem s TermItem pracujete? Z logu to na mě dělá dojem, že opakovaně pouštíte anotaci souborů. Je to tak? Díky

**Comment by marketaadamcova** [comment]
@ledsoft  procházením souboru připojeného ke slovníku procházím text a manuálně ozančuji pojmy buď vybráním již existujícího pojmu nebo vytvořením nového

**Comment by ledsoft** [comment]
Mělo by být vyřešeno, vyzkoušejte.
