### ISSUE TITLE
Snapshot slovníku

### ISSUE THREAD

**Issue by lindatothova** [kbss-cvut/termit-ui#271]
# Popis
Jako editor slovníku
potřebuji novou funkci, která vytvoří snapshot slovníku.

Vytvořené snapshoty slovníku potřebujeme mít dostupné přes API
pro zobrazení v IPR prohlížečce.

## Funkce "snapshot slovníku"
- kaskádově vytvoří i snapshoty dalších slovníků, které jsou navázány přes exactMatch pojem
- snapshoty budou označeny datem a časem, kdy byly provedeny
- v UI - tlačítko "Uložit verzi" na detailu slovníku, dále možnost verzi také smazat

# Využití
Budeme moci vytvářet verze slovníku k určitému datu, jednotlivé verze zobrazovat v prohlížečce. Přepínáním mezi verzemi slovníku bude možné sledovat vývoj např. "definice pojmu" v čase.

# Užitečnost
1. zmíněný scénář bez navrhované funkce realizovat nelze
****

**Comment by MichalMed** [comment]
odevzdáno včetně dokumentace
