### ISSUE TITLE
Import CCI slovníků

### ISSUE THREAD

**Issue by lindatothova** [kbss-cvut/termit-ui#279]
@MichalMed prosím o import CCI slovníků do Termitu od Jirky Buneše z ČAS (viz mail)
[CCI_komplet_20220502.xlsx](https://github.com/kbss-cvut/termit-ui/files/8652251/CCI_komplet_20220502.xlsx)

**Comment by MichalMed** [comment]
nové verze jsou importovány v devu. Prosím o kontrolu a importuji je i do produkce.

**Comment by MichalMed** [comment]
Nové verze jsou na produkci.
