### ISSUE TITLE
Nelze editovat již přiřazené exactMatch pojmy

### ISSUE THREAD

**Issue by lindatothova** [kbss-cvut/termit-ui#282]
# Popis problému
Nelze editovat (odebrat) již přiřazené exactMatch pojmy. ExactMatch pojmy nelze odebrat ze strany pojmu "A", ani ze strany pojmu "B".
Pokud připojím zcela nový exactMatch pojem, tak odebrat lze.

Příklad: https://termit.fel.cvut.cz/ipr/#/vocabularies/slovn%C3%ADk-objekt%C5%AF-zps-georeal/terms/dopravn%C3%AD-ostr%C5%AFvek?namespace=http://slovn%C3%ADk.gov.cz/generick%C3%BD/

# Závažnost problému
2. je to vážný problém

**Comment by MichalMed** [comment]
Mě to nefunguje ani pro nové exactMatch pojmy. Předpokládám, že chyba bude v tom, že se ekvivalence smaže jen na jedné straně, na druhé straně zůstane a jako symetrický vztah se objeví znovu. @ledsoft můžeš to prosím potvrdit?

**Comment by ledsoft** [comment]
Problém je při smazání inverzní části vztahu. Pracuji na řešení.

**Comment by lindatothova** [comment]
Testuji na dev na tomto pojmu:
https://termit.fel.cvut.cz/dev/ipr/#/vocabularies/slovn%C3%ADk-z%C3%A1kona-o-kn/terms/budova?namespace=https://slovn%C3%ADk.gov.cz/generick%C3%BD/&includeImported=false

1. tento pojem má přiřazené dva exactMatch pojmy:
![image](https://user-images.githubusercontent.com/80691594/168583416-ef0e80b1-85be-4e7f-baf3-8a84dfd81be4.png)

2. v editaci odeberu pouze jeden exactMatch pojem "budova - slovník 256/2013", takto uložím:
![image](https://user-images.githubusercontent.com/80691594/168583446-9270ef02-d547-4e73-a4f6-53f34a1b4c58.png)

3. na detailu pojmu se ale nezobrazí žádný exactMatch pojem:
![image](https://user-images.githubusercontent.com/80691594/168583474-eca5073e-8f15-4ebf-b6aa-ec3171d30310.png)

**Comment by lindatothova** [comment]
4. po vrácení exactMatch pojmu "**budova - slovník 256/2013**" se v exactMatch pojmech "**budova - slovník Metropolitního plánu**" zase objeví zpět:
![image](https://user-images.githubusercontent.com/80691594/168585189-1a1c8424-3783-49be-83ca-c47dd594f1f0.png)

**Comment by ledsoft** [comment]
@lindatothova V tomto případě to funguje správně. `exactMatch` je tranzitivní a symetrický vztah. Jelikož **budova - slovník 256/2013** je v `exactMatch` vztahu s **budovou - slovník Metropolitního plánu**, její přidání/odebrání k/od jiného pojmu tranzitivně přidává/odebírá i **budovu - slovník Metropolitního plánu**.

**Comment by lindatothova** [comment]
@ledsoft nj, na tu tranzitivnost jsem úplně zapomněla, díky moc za připomenutí a vysvětlení. Omlouvám se za zbytečné vlny, ale aspoň už si to budu pamatovat :-) Je to tedy v pořádku a může to na produkci. Díky.
