### ISSUE TITLE
Ve SKOS exportu není termit:je-draft

### ISSUE THREAD

**Issue by MichalMed** [kbss-cvut/termit-ui#286]
# Popis
Při exportu dat z TermIta do CSV a Excelu obsahuje atribut draft s hodnotami true nebo false. SKOS export to neobsahuje. Paní Waisová z T-mapy takový požadavek má. Mohli bysme probrat, jestli to má nebo nemá smysl dávat, případně udělat full export, který bude obsahovat všechno (tzn. i mimo SKOS).

# Využití
Umožní plné využití informací uložených v TermItu.

# Užitečnost
3. bylo by hezké ji mít, ale bez problémů se bez ní obejdu

**Comment by lindatothova** [comment]
řešeno v https://github.com/kbss-cvut/termit-ui/issues/296
