### ISSUE TITLE
V JSON/TTL výstupu chybí informace o cs definici

### ISSUE THREAD

**Issue by lindatothova** [kbss-cvut/termit-ui#294]
Ve slovníku DTM https://termit.fel.cvut.cz/ipr/#/vocabularies/dtm?namespace=https://slovn%C3%ADk.gov.cz/datov%C3%BD/ jsem narazila na takovou divnost:

Pokud pojem nemá vyplněnou (cs) definici a zároveň existuje (kromě cs) i en verze detailu pojmu (en definice je vždy prázdná),
potom ve výstupních datech u definice VĚTŠINOU chybí informace o cs definici.
Např. v TTL tedy chybí ""@cs (tzn. je tam jen ""@en, místo ""@en, ""@cs)

- platí pro JSON, TTL výstup
- takto je to u cca 500 pojmů, ale je tam i **6 pojmů, které to mají správně - např.** https://termit.fel.cvut.cz/ipr/#/vocabularies/dtm/terms/stanice-elektrick%C3%A9-s%C3%ADt%C4%9B?namespace=https://slovn%C3%ADk.gov.cz/datov%C3%BD/
![image](https://user-images.githubusercontent.com/80691594/175017444-73a7dbc7-556f-471e-b099-cd65dd093234.png)

**Comment by ledsoft** [comment]
Z hlediska TermItu je "" a nic ekvivalentní, ale je pravda, že to působí nekonzistentně. Navrhuji zbavit se hodnot "" v jakémkoliv jazyce a upravit kód tak, aby k jejich vytváření nedocházelo.
