### ISSUE TITLE
Export slovníku se všemi atributy pojmu

### ISSUE THREAD

**Issue by lindatothova** [kbss-cvut/termit-ui#296]
# Popis
Jako komentátor/editor slovníku
potřebuji exportovat slovník se všemi atributy pojmu (tj. nejen atributy vyjádřené pomocí SKOS),
aby bylo možné provést plnou zálohu dat slovníku (tj. data pro funkci "obnovit ze zálohy")
nebo aby bylo možné přenést plný obsah slovníku do dalšího IS.

**Formáty exportu**
- CSV (do stávajícího CSV exportu doplnit atributy _skos:notation, skos:example, dcterms:references, je-reálným-objektem_)
- Excel (do stávajícího excel exportu doplnit atributy _skos:notation, skos:example, dcterms:references, je-reálným-objektem_)
- Turtle
   - A) SKOS (nechat stávající)
   - B) SKOS+pojmy se stejným významem (nechat stávající)
   - **C) FULL** ( = všechny atributy pojmu z UI včetně _dcterms:references, je-reálným-objektem_)
   - **D) FULL+pojmy se stejným významem**

**Excel export - rozšíření o "user-friendly" formu**
Tento export bychom chtěli upravit tak, aby byl snadno čitelný "pro běžné uživatele TermItu" a zobrazil se v exportovaném souboru **na prvním listu**:
- názvy sloupců v excelu by měly odpovídat názvům atributů v UI TermItu
- atributy s language tagem - označení např. _cs_ umístit až za řetězec znaků např. takto: _Text definice (cs)_, _Text definice (en)_
- všechna IRI vypsat bez "https://slovník.gov.cz"
- atributy s Markdown formátovaným textem převést na prostý text

Stávající forma excel exportu (techničtější zápis) by se zobrazila v exportovaném souboru až **na druhém listu**.

# Využití
Nyní prioritně pro export dat do aplikace JVF DTM - prioritou je tedy export ve formátu **Turtle - varianta D)**

# Užitečnost
1. zmíněný scénář bez navrhované funkce realizovat nelze

**Comment by MichalMed** [comment]
PR řeší první část tasku, tedy přidání atributů do CSV a Excelu. Přidal jsem pouze první tři, dle diskuze dnes dopoledne.

**Comment by lindatothova** [comment]
Potvrzuji, že atribut _je-reálným-objektem_ v žádném z exportů NEPOTŘEBUJEME.
