### ISSUE TITLE
stránka nelze načíst

### ISSUE THREAD

**Issue by marketaadamcova** [kbss-cvut/termit-ui#319]
# Popis problému
Popište:
- už druhý den, nelze načíst hlavní okno aplikace, pří oetvření se na okamžík ukáže ikona "počkejte prosím", poté jen prázná obrazovka
- https://kbss.felk.cvut.cz/termit-csat/#/

![image](https://user-images.githubusercontent.com/100297177/187964623-0720770d-9984-4989-80e2-d1dbac50bdf5.png)

# Závažnost problému
- popište, jak závažný pro práci s TermItem pro Vás problém je:
1. nemohu vůbec pracovat,

**Comment by ledsoft** [comment]
@blcham 
Opraveno. Neběžel server s TermIt instancemi kvůli nedostatku paměti. Problém snad vyřešen a server restartován.
