### ISSUE TITLE
Termit nelze načíst

### ISSUE THREAD

**Issue by marketaadamcova** [kbss-cvut/termit-ui#323]
# Popis problému
Popište:
- při načtení stránky se na chvíli objeví ikona "počkejte proším" a poté jen prázdná obrazovka
- https://kbss.felk.cvut.cz/termit-csat/#/

- možná stejný problém jako minule s pamětí ..

# Závažnost problému
- popište, jak závažný pro práci s TermItem pro Vás problém je:
1. nemohu vůbec pracovat, 

![image](https://user-images.githubusercontent.com/100297177/190954387-326ab879-7083-4f05-91a7-ea62d10467b7.png)

**Comment by ledsoft** [comment]
Opraveno, restartován server.
