### ISSUE TITLE
Vyhledávání podle skos:notation

### ISSUE THREAD

**Issue by MichalMed** [kbss-cvut/termit-ui#326]
# Popis
CCI zkratky jsou uvedené ve skos:notation, ve stávající konfiguraci podle nich ale nelze vyhledávat.  Do stávajícího vyhledávání je tedy potřeba přidat skos:notation.

# Využití
Vyhledávání podle zkratek v CCI (např. BBA atd...)

# Užitečnost
3. bylo by hezké ji mít, ale bez problémů se bez ní obejdu
****

**Comment by ledsoft** [comment]
Implementaci komplikuje několik faktorů.
1. TermIt FTS filtruje výsledky dle jazyka. Ale jelikož skos:notation není mezi mapovanými atributy pojmu, jeho hodnoty language tag v úložišti nemají.
2. CCI zkratky se skládají z 1-3 písmen (dle průzkumu dat). Na ty se obecný FTS v TermItu příliš nehodí, protože ten ke vstupnímu řetězci přidává ještě wildcard (*), aby byla větší šance nalezení výsledků. V kombinaci s interní implementací Lucene indexu úložiště to produkuje nesmyslné výsledky.

Bylo by tedy zřejmě přidat filtrování např. pomocí substringu nebo dokonce přesné shody se vstupním řetězcem a vytvořit příslušný endpoint. Zároveň je třeba promyslet i koncepčnost takového endpointu v rámci TermItu.
