### ISSUE TITLE
V tabe aktivity mi chybí rok kdy se aktivita stala

### ISSUE THREAD

**Issue by blcham** [kbss-cvut/termit-ui#330]
# Popis
Chtel bych videt rok v aktivity diagrame.

# Využití
Mam slovnik na kterem se pracovalo vic nez 2 roky a nebylo to velice lehke z aktivity diagramu zjistit, co to byl za rok, kedze tam neni vizualizovan. Nemit tam vizualizovan rok kdyz je rozmezi aktivit delsi nez 1 rok je minimalne divne. Na obrazku je videt "18 Dec", no nevim o jaky rok jde.

![image](https://user-images.githubusercontent.com/3962237/192897072-c5042c16-42c1-430a-af62-5cd2dad0c970.png)

# Užitečnost
3. bylo by hezké ji mít, ale bez problémů se bez ní obejdu

**Comment by ledsoft** [comment]
@blcham Deployed to development, check it out.

**Comment by blcham** [comment]
@ledsoft looks nice :)
