### ISSUE TITLE
Chtěl bych zjistit kdo pracoval na daném slovníku

### ISSUE THREAD

**Issue by blcham** [kbss-cvut/termit-ui#331]
# Popis
Potreboval bych zjistit kdo pracoval na danem slovniku a to alespon posledni aktivitu na tomto slovniku. Bohuzel v tabu "Change history" vidim jenom aktivity na slovniku a v tabe "Activity" zase neni videt uzivatele, ktery na slovniku pracoval.
![image](https://user-images.githubusercontent.com/3962237/192898294-b1057cb8-cdb1-4bce-a04a-696c2674c06e.png)

Mozne rozsireni:
Umel bych si predstavit nejake info v tabu "Activity", kde by byl nejaky nenapadny filtr na uzivatele, ktery zmeny delali. Podobne jak funguje filtr na "Updated terms a created terms". Jen by to melo byt primarne skryto.

# Využití
Mne se to hodilo k tomu abych zjistil jestli dany clovek na slovniku pracoval, nebo jeste ne. Kdykoli edituje slovnik vice lidi, tak se tato informace hodi.

# Užitečnost
1. zmíněný scénář bez navrhované funkce realizovat nelze, no zit se bez teto funkce da !

**Comment by ledsoft** [comment]
Nahrazeno separátními tickety - #519 a #520.
