### ISSUE TITLE
analyzovaný dokument nelze zobrazit 

### ISSUE THREAD

**Issue by marketaadamcova** [kbss-cvut/termit-ui#333]
# Popis problému
Popište:
- ve slovníku proběhla analýza dokumentu, poté rozklinutí dokumentu se načítá ale není zobrazeno nic. do doby než byla puštěna analýza jsem v dokumentu normálně pracovala
- https://kbss.felk.cvut.cz/termit-csat/#/
- slovník komponent a zádavd - Markéta DP lower case

![image](https://user-images.githubusercontent.com/100297177/192985050-8b9973e4-b756-4465-911a-54f5fbba7c26.png)
![image](https://user-images.githubusercontent.com/100297177/192985333-5c2fa84b-1b6c-4574-8a2b-d5c00aadf607.png)

# Závažnost problému
- popište, jak závažný pro práci s TermItem pro Vás problém je:
1. nemohu vůbec pracovat,

**Comment by ledsoft** [comment]
Dokument měl nevalidní strukturu HTML (neukončený tag `style` hned na začátku `body`). Dle analýzy záloh byla jediná validní verze ta úplně první - záloha z 22. srpna. Od té doby byla struktura poškozená (manuální zásah do obsahu @blcham ?).
Dokument jsem manuálně opravil a dokument už se zobrazuje, tak vyzkoušejte a kdyžtak ticket znovu otevřete.

**Comment by blcham** [comment]
manualni zasah jsem nedelal a nikdo jiny nemel podle mne duvod @ledsoft
