### ISSUE TITLE
Snapshots not found upon reload

### ISSUE THREAD

**Issue by filip-kopecky** [kbss-cvut/termit-ui#335]
When user displays vocabulary snapshot or a snapshotted term and reloads the site, TermIt is not able to find the vocabulary. 
The issue seems to be related to incorrect parsing of the namespace in the request. (missing `verze`)

Valid request: https://kbss.felk.cvut.cz/termit-server-dev/rest/vocabularies/20220630T120131Z?namespace=http%3A%2F%2Fonto.fel.cvut.cz%2Fontologies%2Fslovnik%2Fml-test%2Fverze%2F

Invalid request: https://kbss.felk.cvut.cz/termit-server-dev/rest/vocabularies/20220630T120131Z?namespace=http%3A%2F%2Fonto.fel.cvut.cz%2Fontologies%2Fslovnik%2Fml-test%2F

This behaviour is strange because it doesn't always happen. But I ran into this issue multiple times, so it is pretty much present. Here is a video showing the bug: https://www.loom.com/share/3e6552d8485146dfbd588eb6248627c5

**Comment by ledsoft** [comment]
@FilipKopecky could you verify that it has been fixed on development? It was a stupid minor typo in passing configuration from store to MainView...
