### ISSUE TITLE
Kopie Slovníku Metropolitního plánu

### ISSUE THREAD

**Issue by lindatothova** [kbss-cvut/termit-ui#339]
# Popis
Prosím o kopii slovníku MPP https://termit.fel.cvut.cz/dev/ipr/#/vocabularies/mpp-3.5-np?namespace=https://slovn%C3%ADk.gov.cz/generick%C3%BD/
z dev verze na produkci.

**Comment by MichalMed** [comment]
https://termit.fel.cvut.cz/ipr/#/vocabularies/mpp-3.5-np?namespace=https://slovn%C3%ADk.gov.cz/generick%C3%BD/
