### ISSUE TITLE
komentátor/editor/autor slovníku

### ISSUE THREAD

**Issue by lindatothova** [kbss-cvut/termit-ui#368]
# Popis
Role **komentátor, editor** a nově **autor** slovníku
potřebujeme implementovat již na úroveň slovníku,
aby nešlo editovat slovník, jehož nejsem autorem nebo přiřazeným editorem.

# Užitečnost
Popište, jak užitečná Vám funkce přijde
1. zmíněný scénář bez navrhované funkce realizovat nelze

**Comment by ledsoft** [comment]
# Návrh řešení
- Globální role v TermItu (již existují):
  1. `ADMIN`
  2. `EDITOR`
  3. `ČTENÁŘ`
- Úrovně oprávnění ke slovníku a jeho obsahu
  1. `None` - slovník ani jeho obsah uživatel nevidí
  2. `Read` - uživatel může prohlížet slovník, jeho obsah, přidávat komentáře, exportovat obsah slovníku, zobrazit revizi, zobrazit/stáhnout dokument(y) slovníku
  3. `Write` - `Read` + uživatel může editovat slovník a jeho obsah, analyzovat definice pojmů slovníku, analyzovat obsah dokumentu slovníku, vytvořit/upravit dokumenty slovníku
  4. `Security` - `Write` + uživatel může slovník a jeho obsah mazat, obnovit slovník ze zálohy (SKOS import), vytvořit/smazat revizi slovníku, smazat dokument slovníku, přiřazovat úrovně oprávnění jiným uživatelům a skupinám uživatelů
 
Uživatele bude možné dávat do skupin (skupiny mohou upravovat pouze uživatelé v roli `ADMIN`). Každý uživatel může být v 0 či více skupinách.

Slovník bude mít access control list (ACL), který se skládá z:
- Mapy uživatelů a úrovní oprávnění, která mají vůči danému slovníku
- Mapy skupin uživatelů a úrovní oprávnění, která mají vůči danému slovníku. Všichni uživatelé z dané skupiny mají oprávnění přiřazené celé skupině.

Při vytvoření nového slovníku:
1. Dostane jeho autor automaticky úroveň oprávnění `Security`
2. Autor zvolí, jaká práva budou aplikována pro uživatelské role. Defaultní nastavení dává uživatelům s rolí `EDITOR` i `ČTENÁŘ` úroveň oprávnění `Read`
3. Při přiřazování práv jednotlivým uživatelům může uživatel s rolí `EDITOR` dostat maximálně úroveň `Security`, uživatel s rolí `ČTENÁŘ` může dostat maximálně úroveň `Write`.
4. Při přiřazování práv uživatelským skupinám lze vybrat maximálně úroveň `Write`. Tj., `Security` přístup lze udělit jen a pouze konkrétním uživatelům.

Administrátoři TermItu mají automaticky ke všem slovníkům oprávnění na úrovni `Security`.

Při přístupu ke slovníku se rozhodování řídí níže přiloženým rozhodovacím diagramem.
![TermIt-vocabulary-acl](https://user-images.githubusercontent.com/2676156/217011306-ecf823d3-0695-4ffe-9769-a25f3beec3a3.png)

_Update_: Uživatelská práva zpřesněna dle zpětné vazby.

**Comment by lindatothova** [comment]
Posílám upřesnění:

- úroveň oprávnění None - ANO
- uživatelské skupiny - ANO
- při vytvoření nového slovníku - varianta 2.B
