### ISSUE TITLE
Aktivní odkazy v "Dalších atributech"

### ISSUE THREAD

**Issue by lindatothova** [kbss-cvut/termit-ui#369]
# Popis
Na detailu pojmu v záložce Další atributy
hodnota atributu dcterms:references by měla fungovat jako klikatelný odkaz,
pokud tento odkaz začíná řetězcem "http"

# Využití
Nezdržuji se kopírováním odkazu..

# Užitečnost
2. zmíněný scénář lze bez funkce realizovat, ale zdržuje mě to

**Comment by ledsoft** [comment]
Update: aktivní odkazy by v dalších atributech měly být u všech properties, ne jen dcterms:references. Stejně tak by bylo vhodné rozšířit pattern pro odkazy i např. na `ftp`

**Comment by lindatothova** [comment]
Otestováno, v pořádku.
