### ISSUE TITLE
Pád aplikace při zadání 'ú' do Souvisejících pojmů

### ISSUE THREAD

**Issue by filip-kopecky** [kbss-cvut/termit-ui#378]
# Popis problému
Při editaci pojmu a zadání 'ú' do vyhledávacího pole u `Pojmy se stejným významem` dojde k pádu aplikace. Instance: https://kbss.felk.cvut.cz/termit-dev/ 
Stacktrace: 

VirtualizedTreeSelect.js:230 Uncaught (in promise) TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'Array'
    |     index 0 -> object with constructor 'Object'
    |     property 'parentTerms' -> object with constructor 'Object'
    --- property 'subTerms' closes the circle
    at JSON.stringify (<anonymous>)
    at n.value (VirtualizedTreeSelect.js:230:32)
    at VirtualizedTreeSelect.js:250:12
    at Array.forEach (<anonymous>)
    at n.value (VirtualizedTreeSelect.js:249:36)
    at VirtualizedTreeSelect.js:250:12
    at Array.forEach (<anonymous>)
    at n.value (VirtualizedTreeSelect.js:249:36)
    at VirtualizedTreeSelect.js:182:14
    at Array.forEach (<anonymous>)
    
Problém může být čistě v datech, ale to neomlouvá vyhození chyby takovým stylem že padne celá appka.

# Závažnost problému
2. je to vážný problém,

**Comment by ledsoft** [comment]
Platí i pro jiná písmena, jde o problém vycházející ze struktury dat.
