### ISSUE TITLE
Pro nahrany dokument se nezobrazuje volba view

### ISSUE THREAD

**Issue by blcham** [kbss-cvut/termit-ui#394]
Reportovano od @lalisand

# Popis problému
Popište:
Uploadoval jsem 2 dokumenty do deploymentu "demo" do slovnika "Aviation safety regulations" viz. https://kbss.felk.cvut.cz/termit-demo/#/vocabularies/aviation-safety-regulations?namespace=http://onto.fel.cvut.cz/ontologies/slovnik/. U druheho dokumentu se v tabu "Document" zobrazuje moznost "View". U toho prvniho dokumentu vsak tuto moznost nemam -- to je ten bug.

# Závažnost problému
1. nemohu vůbec pracovat, nemuzu totiz delat textovou analyzu.

![image](https://user-images.githubusercontent.com/3962237/224488523-9d039215-b70e-4225-8b84-459141f66dec.png)

![image](https://user-images.githubusercontent.com/3962237/224488560-9c03b384-fd9a-4541-a1c7-69bc708a3e8a.png)

**Comment by blcham** [comment]
Jeste info navic -- dokumenty byly nahrany v stejny den cca. 9.3.2023. U "vadneho" dokumentu nefunguje ani tlacitko "Download"/"Download original".

**Comment by ledsoft** [comment]
Update based on log examination and reproducing the issue:
- The uploaded file exceeded the maximum allowed size (10MB in this case). TermIt does show an error message, but relatively briefly.
- Content-related buttons should not be displayed in this case. This is the bug.
- Ideally, the UI should not allow submitting a file exceeding the size limit in the first place.
