### ISSUE TITLE
Nefunguje tlačítko "view" v dokumentoch k slovníkom

### ISSUE THREAD

**Issue by lalisand** [kbss-cvut/termit-ui#395]
V demo-termit som vytvoril slovník (aviation safety regulations), pridal dokument, tlačítko "view" sa zobrazí, ale po kliknutí naň sa nič nestane. V konzole F12 to píše, že by som mal zapnúť JavaScript, ale ten zapnutý mám. Termit som spustil na verzii Google Chrome 110.0.5481.180.

# Závažnost problému
1. nemohu vůbec pracovat, 

![Error_termit](https://user-images.githubusercontent.com/94048408/224634985-e30102bd-4447-4b39-b4cd-4a9aba34f1f3.png)

**Comment by ledsoft** [comment]
Possible duplicate of #394 ?

**Comment by ledsoft** [comment]
Fixed.
