### ISSUE TITLE
Nasazení TermItu pro CCI

### ISSUE THREAD

**Issue by lindatothova** [kbss-cvut/termit-ui#401]
Prosím o nasazení nové instance Termitu pro slovníky CCI. Default jazyk pojmu bude angličtina.

Slovníky k migraci:

- https://termit.fel.cvut.cz/ipr/#/vocabularies/bim-funk%C4%8Dn%C3%AD-syst%C3%A9m-0?namespace=http://slovn%C3%ADk.gov.cz/generick%C3%BD/
- https://termit.fel.cvut.cz/ipr/#/vocabularies/bim-komponenty-0?namespace=http://slovn%C3%ADk.gov.cz/generick%C3%BD/
- https://termit.fel.cvut.cz/ipr/#/vocabularies/bim-stavebn%C3%AD-entity-0?namespace=http://slovn%C3%ADk.gov.cz/generick%C3%BD/
- https://termit.fel.cvut.cz/ipr/#/vocabularies/bim-technick%C3%BD-syst%C3%A9m-0?namespace=http://slovn%C3%ADk.gov.cz/generick%C3%BD/
- https://termit.fel.cvut.cz/ipr/#/vocabularies/bim-vybudovan%C3%A9-prostory-0?namespace=http://slovn%C3%ADk.gov.cz/generick%C3%BD/

**Comment by MichalMed** [comment]
Na https://termit.fel.cvut.cz/cas/#/vocabularies jsou naimportovány zmíněné slovníky. Proím o kontrolu, potom smažu z IPR.

**Comment by ledsoft** [comment]
@lindatothova Můžeme zavřít?

**Comment by lindatothova** [comment]
Zjistím u Jirky Buneše, zda si to nové nasazení vyzkoušeli a zkontrolovali.
