### ISSUE TITLE
Promazání slovníků na DEV

### ISSUE THREAD

**Issue by lindatothova** [kbss-cvut/termit-ui#403]
Prosím o promazání slovníků na DEV dle tohoto seznamu.
Pokud mazaný slovník obsahuje vazbu na jiný slovník, potom tato vazba bude odstraněna.

1. https://termit.fel.cvut.cz/dev/ipr/#/vocabularies/objekty-zps-georeal?namespace=https://slovn%C3%ADk.gov.cz/generick%C3%BD/
2. https://termit.fel.cvut.cz/dev/ipr/#/vocabularies/slovnik-pro-import?namespace=https://slovn%C3%ADk.gov.cz/generick%C3%BD/
3. https://termit.fel.cvut.cz/dev/ipr/#/vocabularies/slovn%C3%ADk-test-0?namespace=https://slovn%C3%ADk.gov.cz/generick%C3%BD/
4. https://termit.fel.cvut.cz/dev/ipr/#/vocabularies/slovn%C3%ADk-test-2?namespace=https://slovn%C3%ADk.gov.cz/generick%C3%BD/
5. https://termit.fel.cvut.cz/dev/ipr/#/vocabularies/jvf-dtm?namespace=https://slovn%C3%ADk.gov.cz/datov%C3%BD/
6. https://termit.fel.cvut.cz/dev/ipr/#/vocabularies/slovn%C3%ADk-test-3?namespace=https://slovn%C3%ADk.gov.cz/generick%C3%BD/
7. https://termit.fel.cvut.cz/dev/ipr/#/vocabularies/slovn%C3%ADk-test-4?namespace=https://slovn%C3%ADk.gov.cz/generick%C3%BD/
8. https://termit.fel.cvut.cz/dev/ipr/#/vocabularies/slovn%C3%ADk-test-5-definition?namespace=https://slovn%C3%ADk.gov.cz/generick%C3%BD/
9. https://termit.fel.cvut.cz/dev/ipr/#/vocabularies/slovn%C3%ADk-test-5-preflabel?namespace=https://slovn%C3%ADk.gov.cz/generick%C3%BD/
10. https://termit.fel.cvut.cz/dev/ipr/#/vocabularies/slovn%C3%ADk-test-5-scopenote?namespace=https://slovn%C3%ADk.gov.cz/generick%C3%BD/
11. https://termit.fel.cvut.cz/dev/ipr/#/vocabularies/dtm?namespace=https://slovn%C3%ADk.gov.cz/datov%C3%BD/
12. https://termit.fel.cvut.cz/dev/ipr/#/vocabularies/dtm-0-0?namespace=https://slovn%C3%ADk.gov.cz/datov%C3%BD/
13. https://termit.fel.cvut.cz/dev/ipr/#/vocabularies/slovn%C3%ADk-objekt%C5%AF-zps-3?namespace=http://slovn%C3%ADk.gov.cz/generick%C3%BD/
14. https://termit.fel.cvut.cz/dev/ipr/#/vocabularies/slovn%C3%ADk-objekt%C5%AF-zps-georeal?namespace=http://slovn%C3%ADk.gov.cz/generick%C3%BD/
15. https://termit.fel.cvut.cz/dev/ipr/#/vocabularies/slovn%C3%ADk-test-6?namespace=https://slovn%C3%ADk.gov.cz/generick%C3%BD/
16. https://termit.fel.cvut.cz/dev/ipr/#/vocabularies/testovac%C3%AD-slovn%C3%AD-bune%C5%A1?namespace=https://slovn%C3%ADk.gov.cz/generick%C3%BD/
17. https://termit.fel.cvut.cz/dev/ipr/#/vocabularies/testovac%C3%AD-slovn%C3%ADk---alena-zme%C5%A1kalov%C3%A1?namespace=https://slovn%C3%ADk.gov.cz/generick%C3%BD/
18. https://termit.fel.cvut.cz/dev/ipr/#/vocabularies/testovac%C3%AD-slovn%C3%ADk---jan-kolomazn%C3%ADk?namespace=https://slovn%C3%ADk.gov.cz/generick%C3%BD/
19. https://termit.fel.cvut.cz/dev/ipr/#/vocabularies/testovac%C3%AD-slovn%C3%ADk-hany-peckelov%C3%A9?namespace=https://slovn%C3%ADk.gov.cz/generick%C3%BD/
20. https://termit.fel.cvut.cz/dev/ipr/#/vocabularies/testovac%C3%AD-slovn%C3%ADk-katky-vrbove?namespace=https://slovn%C3%ADk.gov.cz/generick%C3%BD/
21. https://termit.fel.cvut.cz/dev/ipr/#/vocabularies/testovac%C3%AD-slovn%C3%ADk-leo%C5%A1e-mazala?namespace=https://slovn%C3%ADk.gov.cz/generick%C3%BD/
22. https://termit.fel.cvut.cz/dev/ipr/#/vocabularies/testovac%C3%AD-slovn%C3%ADk-m.-meda?namespace=https://slovn%C3%ADk.gov.cz/generick%C3%BD/
23. https://termit.fel.cvut.cz/dev/ipr/#/vocabularies/testovac%C3%AD-slovn%C3%ADk-michal-meda?namespace=https://slovn%C3%ADk.gov.cz/generick%C3%BD/
24. https://termit.fel.cvut.cz/dev/ipr/#/vocabularies/testovac%C3%AD-slovn%C3%ADk-r%C3%BDpara-v%C3%ADta?namespace=https://slovn%C3%ADk.gov.cz/generick%C3%BD/
25. https://termit.fel.cvut.cz/dev/ipr/#/vocabularies/testovac%C3%AD-slovn%C3%ADk-v%C4%8D?namespace=https://slovn%C3%ADk.gov.cz/generick%C3%BD/
26. https://termit.fel.cvut.cz/dev/ipr/#/vocabularies/testovac%C3%AD-slovn%C3%ADk-%C5%A1t?namespace=https://slovn%C3%ADk.gov.cz/generick%C3%BD/
27. https://termit.fel.cvut.cz/dev/ipr/#/vocabularies/slovn%C3%ADk-re%C3%A1ln%C3%BDch-objekt%C5%AF-dtm?namespace=https://slovn%C3%ADk.gov.cz/generick%C3%BD/
28. https://termit.fel.cvut.cz/dev/ipr/#/vocabularies/testovaci-slovnik?namespace=https://slovn%C3%ADk.gov.cz/generick%C3%BD/
29. https://termit.fel.cvut.cz/dev/ipr/#/vocabularies/testovaci-slovnik-0?namespace=https://slovn%C3%ADk.gov.cz/generick%C3%BD/
30. https://termit.fel.cvut.cz/dev/ipr/#/vocabularies/testpk5?namespace=https://slovn%C3%ADk.gov.cz/generick%C3%BD/

**Comment by MichalMed** [comment]
Smazáno včetně změn a snapshotů. Prosím o kontrolu

**Comment by lindatothova** [comment]
@MichalMed Ještě prosím domazat tyto slovníky:
16. https://termit.fel.cvut.cz/dev/ipr/#/vocabularies/testovac%C3%AD-slovn%C3%AD-bune%C5%A1?namespace=https://slovn%C3%ADk.gov.cz/generick%C3%BD/
28. https://termit.fel.cvut.cz/dev/ipr/#/vocabularies/testovaci-slovnik?namespace=https://slovn%C3%ADk.gov.cz/generick%C3%BD/
29. https://termit.fel.cvut.cz/dev/ipr/#/vocabularies/testovaci-slovnik-0?namespace=https://slovn%C3%ADk.gov.cz/generick%C3%BD/

Slovníky DTM byly omylem smazány všechny, pro testování by se nám ale DTM slovník na DEVu hodil. Můžeš nám na DEV nakopírovat DTM slovník z produkce? Je to tento:
https://termit.fel.cvut.cz/ipr/#/vocabularies/dtm?namespace=https://slovn%C3%ADk.gov.cz/datov%C3%BD/

(Vazby mezi DTM slovníkem a slovníky, které na devu neexistují, zaniknou.)

**Comment by MichalMed** [comment]
Domazal jsem zbývající slovníky. DTM v seznamu je (číslo 11.) ale dal jsem ho zpátky. https://termit.fel.cvut.cz/dev/ipr/#/vocabularies/dtm/terms/elektrick%C3%A9-veden%C3%AD-skupina?namespace=https://slovn%C3%ADk.gov.cz/datov%C3%BD/ Zkontroluj si prosím i ty vazby na neexistující slovníky (v DTM nevím o žádné, která by tam měla být, tak nevím, jak zkontrolovat).

**Comment by lindatothova** [comment]
Prosím o vrácení slovníku **dtm-0-1** (ten má právě ty exactMatch vazby, pokud si to dobře pamatuju):
https://termit.fel.cvut.cz/dev/ipr/#/vocabularies/dtm-0-1?namespace=https://slovn%C3%ADk.gov.cz/datov%C3%BD/

č. 11 - můžeš nechat mezi smazanými:
https://termit.fel.cvut.cz/dev/ipr/#/vocabularies/dtm?namespace=https://slovn%C3%ADk.gov.cz/datov%C3%BD/

**Comment by MichalMed** [comment]
Slovník dtm-0-1 v produkci není, takže ho nemám odkud vrátit. DTM jsem tedy nechal to z produkce. V produkci se nic neměnilo, tam by to mělo být správně všechno.

**Comment by lindatothova** [comment]
OK, díky.
