### ISSUE TITLE
Dogenerování dokumentu slovníku

### ISSUE THREAD

**Issue by lindatothova** [kbss-cvut/termit-ui#409]
# Popis
Prosím o vytvoření dokumentu slovníku u těch slovníků, které ho nyní nemají.
Týká se to těchto instancí:
https://termit.fel.cvut.cz/cas/#
https://termit.fel.cvut.cz/ipr/#

# Využití
Ke slovníku půjde přidat nový zdroj na detailu slovníku v záložce Dokument.

# Užitečnost
1. zmíněný scénář bez navrhované funkce realizovat nelze

**Comment by ledsoft** [comment]
Hotovo, @lindatothova prosím o kontrolu a zavření.
