### ISSUE TITLE
Úprava CCI slovníků - ČAS TermIt

### ISSUE THREAD

**Issue by lindatothova** [kbss-cvut/termit-ui#410]
Prosím o úpravu CCI slovníků na instanci https://termit.fel.cvut.cz/cas/#/login

**1) Změna struktury slovníků**
Nyní je CCI slovníků 5 a v nové struktuře budou jen 4 takto:

- _CCI - Construction entity_ ZŮSTÁVÁ (BEZ ZMĚNY)
- _CCI - Built Space_ ZŮSTÁVÁ (POUZE ZMĚNA NÁZVU Z PŮVODNÍHO _CCI - Space_)
- _CCI - Construction element_: Vznikne nově a to nadřazeně nad zbývajícími třemi slovníky (CCI - Component, CCI - Functional system, CCI - Technical system). Tzn. z názvů slovníků (CCI - Component, CCI - Functional system, CCI - Technical system) se stanou názvy pojmů a v nově vzniklém slovníku CCI - Construction element budou tyto tři pojmy hierarchicky nejvýše. Pojem CCI - Component bude dále obsahovat všechny pojmy, které obsahuje stávající slovník CCI - Component. Analogicky to bude platit i pro pojmy CCI - Functional system, CCI - Technical system.

- _CCI - Construction complex_ NOVÝ

**2) Změna IRI, atribut Notation**

- **base IRI** ([https://slovník.gov.cz/generický/](https://xn--slovnk-7va.gov.cz/generick%C3%BD/)) - změnit na https://cci-collaboration.org/
- **IRI slovníku** - vybuduje se z anglického názvu slovníku (CCI - Construction entity, CCI - Built Space, CCI - Construction element, CCI - Construction complex)
- **IRI pojmu** - vybuduje se z CCI kódu (tj. z Notation)
- **změna pro vyplnění atributu Notation** - nově tam budou ponechána podtržítka + přidají se i písmena uzlu
- příklad IRI pojmu: [https://cci-collaboration.org/cci-construction-element/term/L-A__](https://cci-collaboration.org/cci-construction-element/term/L-A__)

**3) Názvy tří (nových) hierarchicky nejvyšších pojmů ve slovníku CCI - Construction element** (navazuje na bod 1)
Dle přání JB jsou názvy v množném čísle.
AJ:

- Functional systems
- Technical systems
- Components

ČJ:

- Funkční systémy
- Technické systémy
- Komponenty

Je potřeba ještě navrhnout IRI těchto tří pojmů.

**Comment by MichalMed** [comment]
jsou nasazeny slovníky Built Space, Construction Entity a Construction Element. Čekám na podklady pro Construction Complex.

**Comment by lindatothova** [comment]
Poslední požadavky na úpravu CCI slovníků včetně předávaných dat jsou dostupné v tomto Slack vlákně:
https://ontologieurba-zvl2269.slack.com/archives/C02LQLZV14G/p1687204910967999
