### ISSUE TITLE
Stromečková struktura filtrovaná dle "stavu pojmu"

### ISSUE THREAD

**Issue by lindatothova** [kbss-cvut/termit-ui#416]
# Popis problému
Stromečková struktura pojmů se nezobrazuje správně, pokud použiji filtraci pojmů dle atributu "stav pojmu".
Např. pokud vyberu zobrazení pouze _schválených_ pojmů, potom hierarchicky nadřazený pojem, který je _rozpracovaný_, se již nezobrazí (strom pojmů zde končí), ačkoliv některé jeho podřazené pojmy jsou _schválené_ (ale už nejsou zobrazené).

**nadřazený rozpracovaný:** https://termit.fel.cvut.cz/ipr/#/vocabularies/dtm/terms/dopl%C5%88kov%C3%A9-re%C3%A1ln%C3%A9-objekty-modelu-dtm?namespace=https://slovn%C3%ADk.gov.cz/datov%C3%BD/&includeImported=false

**podřazený schválený**: https://termit.fel.cvut.cz/ipr/#/vocabularies/dtm/terms/hr%C3%A1z?namespace=https://slovn%C3%ADk.gov.cz/datov%C3%BD/

# Závažnost problému
2. je to vážný problém

**Comment by ledsoft** [comment]
Nahrazeno filtrováním dle stavu pojmu ve facetovém vyhledávání.
