### ISSUE TITLE
ČAS TermIt - import dalších jazykových verzí slovníků

### ISSUE THREAD

**Issue by lindatothova** [kbss-cvut/termit-ui#425]
Prosím o import estonské, švédské a dánské jazykové verze těchto slovníků:
https://termit.fel.cvut.cz/cas/#/vocabularies/cci-construction-complex?namespace=https://cci-collaboration.org/
https://termit.fel.cvut.cz/cas/#/vocabularies/cci-construction-entity-0?namespace=https://cci-collaboration.org/
https://termit.fel.cvut.cz/cas/#/vocabularies/cci-construction-element-0?namespace=https://cci-collaboration.org/
https://termit.fel.cvut.cz/cas/#/vocabularies/cci-built-space-0?namespace=https://cci-collaboration.org/

**Comment by MichalMed** [comment]
čekám na vstupní data
