### ISSUE TITLE
IPR TermIt - kopie slovníků

### ISSUE THREAD

**Issue by lindatothova** [kbss-cvut/termit-ui#426]
Prosím o vytvoření kopie těchto dvou slovníků - vše na produkčním prostředí.

1. Slovník vyhlášky č. 393/2020 Sb., o digitální technické mapě kraje ve znění k 6.10.2020
https://termit.fel.cvut.cz/ipr/#/vocabularies/2020?namespace=https://slovn%C3%ADk.gov.cz/legislativn%C3%AD/sb%C3%ADrka/393/

2. Slovník datového modelu DTM
https://termit.fel.cvut.cz/ipr/#/vocabularies/dtm?namespace=https://slovn%C3%ADk.gov.cz/datov%C3%BD/

**Názvy a IRI kopií slovníků**
1. Slovník vyhlášky č. 393/2020 Sb., o digitální technické mapě kraje ve znění k 1.7.2023
IRI: https://slovník.gov.cz/legislativní/sbírka/393/2020-20230701

2. Slovník datového modelu DTM po novele platné od 1.7.2023
IRI: https://slovník.gov.cz/datový/dtm-20230701

**Pokyny k vytvoření kopií jsou uvedeny v horní části tohoto schématu**
![novela_DTM](https://github.com/kbss-cvut/termit-ui/assets/80691594/94e21550-1cd0-4fae-abcf-1a9816b330b1)

**Comment by MichalMed** [comment]
hotovo, slovníky jsou nahrané v produkci:

* https://termit.fel.cvut.cz/ipr/#/vocabularies/2020-20230701?namespace=https://slovn%C3%ADk.gov.cz/legislativn%C3%AD/sb%C3%ADrka/393/
* https://termit.fel.cvut.cz/ipr/#/vocabularies/dtm-20230701-0?namespace=https://slovn%C3%ADk.gov.cz/datov%C3%BD/
