### ISSUE TITLE
Access Control List is not created

### ISSUE THREAD

**Issue by MichalMed** [kbss-cvut/termit-ui#434]
# Popis problému
Popište:
- při importu slovníku přes TermIt UI se nevytvoří Access Control List, je potřeba restartovat TermIt.

# Závažnost problému
2. je to vážný problém,

**Comment by lindatothova** [comment]
Ještě doplňuji, kdyby to něčemu pomohlo - během 24 hod po importu slovníku se systém choval tak, jako by ACL existoval, tj. přístup ke slovníku měli i ostatní uživatelé (nejen admin). Poté došlo najednou k omezení přístupu jen na admina.
