### ISSUE TITLE
IPR Termit / Slovník zeleň / import dat 

### ISSUE THREAD

**Issue by lindatothova** [kbss-cvut/termit-ui#436]
Prosím o import dat do "Slovníku zeleně k 30.9.2023":
https://termit.fel.cvut.cz/ipr/#/vocabularies/slovn%C3%ADk-zelen%C4%9B-k-30.9.2023?namespace=https://slovn%C3%ADk.gov.cz/generick%C3%BD/

Data:
[Zelen_import_Termit.xlsx](https://github.com/kbss-cvut/termit-ui/files/12715551/Zelen_import_Termit.xlsx)
Pozn. ke struktuře dat:
Oddělovač jednotlivých hodnot atributu Reference je čárka a mezera ", "

**Comment by MichalMed** [comment]
Provedl jsem transformaci a slovník je nahraný zde: https://termit.fel.cvut.cz/ipr/#/vocabularies/slovn%C3%ADk-zelen%C4%9B?namespace=https://slovn%C3%ADk.gov.cz/generick%C3%BD/
Prosím, o kontrolu a případné uzavření ticketu.
