### ISSUE TITLE
Kopie slovníků DTM pro novelu vyhlášky 2024

### ISSUE THREAD

**Issue by lindatothova** [kbss-cvut/termit-ui#438]
Prosím o vytvoření kopie těchto dvou slovníků - vše na produkčním prostředí.

Slovník vyhlášky č. 393/2020 Sb., o digitální technické mapě kraje ve znění k 1.7.2023
https://termit.fel.cvut.cz/ipr/#/vocabularies/2020-20230701?namespace=https://slovn%C3%ADk.gov.cz/legislativn%C3%AD/sb%C3%ADrka/393/

Slovník datového modelu DTM ve verzi k 1. 7. 2023
https://termit.fel.cvut.cz/ipr/#/vocabularies/dtm-20230701?namespace=https://slovn%C3%ADk.gov.cz/datov%C3%BD/

**Názvy a IRI kopií slovníků**

Slovník vyhlášky č. 393/2020 Sb., o digitální technické mapě kraje ve znění k 1.7.2024
IRI: [https://slovník.gov.cz/legislativní/sbírka/393/2020-20240701](about:blank)

Slovník datového modelu DTM ve verzi k 1. 7. 2024
IRI: [https://slovník.gov.cz/datový/dtm-20240701](about:blank)

**Pokyny k vytvoření kopií jsou uvedeny v tomto schématu**
![novela_DTM_DRUHA_2](https://github.com/kbss-cvut/termit-ui/assets/80691594/85a1b6a6-8746-40df-825b-35c4235a3217)

**Comment by MichalMed** [comment]
Hotovo, prosím o kontrolu
