### ISSUE TITLE
Hodnoty atributu dcterms:references nelze odstranit

### ISSUE THREAD

**Issue by lindatothova** [kbss-cvut/termit-ui#442]
# Popis problému
U objektu https://termit.fel.cvut.cz/ipr/#/vocabularies/dtm-20240701/terms/vodn%C3%AD-n%C3%A1dr%C5%BE?namespace=https://slovn%C3%ADk.gov.cz/datov%C3%BD/ nejdou samazat v atributech přidané reference (obrázky), když pojem odstraním a vytvořím ho znovu (čistý, bez obsahu), po uložení se tam obrázky znovu ukáží.

# Závažnost problému
2. je to vážný problém

**Comment by ledsoft** [comment]
**Interní poznámka**: Je způsobeno tím, že původně aplikace ukládala tyto hodnoty jako URI, ale cca od června je považuje za string. To ale způsobuje, že původně uložené IRI nejsou mazány, protože to hledá stringy. Bude vyřešeno migrací dat na aktuálně podporovaný datový typ.
