### ISSUE TITLE
Nelze editovat název dokumentu slovníku

### ISSUE THREAD

**Issue by lindatothova** [kbss-cvut/termit-ui#452]
Po uložení nového názvu dokumentu slovníku,
Termit hlásí chybu v datech - viz obr.:

![image](https://github.com/kbss-cvut/termit-ui/assets/80691594/c7ec6ead-577a-4c76-b181-71e182c35a79)

Testovaný slovník: https://termit.fel.cvut.cz/dev/ipr/#/vocabularies/slovn%C3%ADk-uap-2020---200-m%C4%9Bsto---3.1---test?namespace=https://slovn%C3%ADk.gov.cz/generick%C3%BD/

**Comment by ledsoft** [comment]
Opraveno.

**Comment by lindatothova** [comment]
Vyzkoušeno, funguje správně. Díky za opravu.
