### ISSUE TITLE
Ve správě přístupu slovníku nelze přidat nový záznam

### ISSUE THREAD

**Issue by lindatothova** [kbss-cvut/termit-ui#453]
# Popis problému
Instance: https://termit.fel.cvut.cz/dev/ipr/#/
Na detailu slovníku ve správě přístupu nelze přidat nový záznam:

- otevřu okno Nový záznam řízení přístupu
- vyplním držitele a úroveň oprávnění
- akce Uložit neprovede ale žádné změny ve správě přístupu

# Závažnost problému
2. je to vážný problém

**Comment by ledsoft** [comment]
Opraveno

**Comment by lindatothova** [comment]
Vyzkoušeno, funguje správně. Díky za opravu.
