### ISSUE TITLE
Selektor existujících pojmů v anotátoru

### ISSUE THREAD

**Issue by lindatothova** [kbss-cvut/termit-ui#456]
# Popis
Jako editor slovníku
při práci s dokumentem v prostředí anotátoru
potřebuji zlepšit uživatelskou orientaci ve velkém počtu navržených/potvrzených výskytů existujících pojmů v celém (často rozsáhlém) textu dokumentu. **Tzn. potřebuji mít přehled o všech výskytech vybraného existujícího pojmu napříč celým dokumentem.**

Ideálně kdyby šlo UI anotátoru obohatit o selector s existujícími pojmy slovníku. Po výběru existujícího pojmu by se v dokumentu zvýraznily všechny navržené/potvrzené výskyty právě tohoto pojmu.

Tuto funkcionalitu by bylo možné do budoucna rozšířit i na výskyty “nových” pojmů. Momentálně to není nutné. Pravděpodobně to bude složitější řešení, když pojmy neexistují fyzicky v DB.

# Užitečnost
2. zmíněný scénář lze bez funkce realizovat, ale zdržuje mě to

**Comment by MichalMed** [comment]
tested on dev without major issues

**Comment by MichalMed** [comment]
možné vylepšení:
* vyskakovací okno se zavírá opětovným kliknutím na Find (chybí křížek pro zavření okna, může být neintuitivní)
* vyhledáváat i výskyty z jiných slovníků
* tlačítka předchozí/další pro skrolování na konkrétní výskyt pojmu v textu (v dlouhých textech může být slžité výskyt vůbec najít, i když je vybarven)

**Comment by lindatothova** [comment]
Díky, já mám také otestováno a napadá mě k tomu následující:

- [x] pokud to není složité, tak prosím o možnost pohybu v drop-down listu také pomocí šipek + enter pro select (tedy nejen select pomocí myši)
- [x] sice mi to v zadání ticketu chybí, ale hodilo by se nám doplnit ještě to, co zmiňuje @MichalMed, tedy prosím o doplnění šipek vpřed/vzad pro posun po jednotlivých zvýrazněných výskytech právě kvůli posunu obrazovky na výskyt. Nevím, jak ten posun po výskytech graficky realizovat - např. další barvou zvýraznění? (nejčastěji se asi používá oranžová)
- [x] prosím o přidání křížku pro zavření vyhledávacího okna, to bude jistota
- [x] grafika zvýrazněných potvrzených výskytů - mohlo by být černé orámování ještě tučnější? Tak aby byly zvýrazněné potvrzené výskyty opticky výraznější než zvýrazněné NEpotvrzené výskyty
- [x] šlo by zařídit, aby selektor pro vyhledávání nabízel vždy pojmy z toho slovníku, který byl použit pro spuštění poslední textové analýzy dokumentu? A dávalo by vám toto nastavení smysl?
