### ISSUE TITLE
Přepoužití existujících potvrzených výskytů při opakované anotaci souboru

### ISSUE THREAD

**Issue by ledsoft** [kbss-cvut/termit-ui#461]
Při opakované anotaci (nebo re-uploadu mírně upraveného souboru a jeho anotaci) se ztratí již potvrzené výskyty. To vyžaduje, aby anotovaný obsah znovu prošel uživatel a potvrdil výskyty pojmů. TermIt by měl být schopen na základě selektorů rozpoznat již potvrzené výskyty z předchozí anotace a automaticky je opět označit jako potvrzené. Tím uživateli ušetří čas při opakovaném zpracovávání souborů.

# Užitečnost
2. zmíněný scénář lze bez funkce realizovat, ale zdržuje mě to
****

**Comment by MichalMed** [comment]
Postup a výsledky testování:
1) tvorba nového slovníku s několika pojmy, nahrání dokumentu a anotace. Po anotaci některé výskyty potvrzeny, některé odmítnuty, některé navrhované přijaty s vytvořením nového pojmu a někde vytvořenbíé nové anotace a nového pojmu. Poté opětovná anotace:
    a. stávající pojmy zůstaly oanotované, ale po opakované anotaci se přes ně udělaly nové návrhy stejných pojmů, na některých místech jsou tedy přes sebe vícenásobné výskyty stejných pojmů,
    b. odmítnuté návrhy nová anotace nabízí znovu, je potřeba je znovu odmítnout,
    c. po potvrzení návrhu nového pojmu a jeho vytvoření jsou navrhované výskyty nových pojmů nahrazeny navrhovanými výskyty existujících pojmů, to je podle mě správné chování.
2) z html souboru na disku jsem smazal jeden odstavec a soubor nahrál znovu k dokumentu a otevřel ho:
    * v sopuboru nebyly žádné anotace, to je asi správně,
3) spustil jsem nad souborem novou anotaci,
    * v souboru nejsou žádné potvrzené anotace, to je asi špatně.

**Comment by MichalMed** [comment]
Proběho testování stejným způsobem jako minule, S výjimkou opakovaného návrhu odmítnutých výskytů byly všechny chyby opraveny.
