### ISSUE TITLE
Úprava grafiky anotátoru

### ISSUE THREAD

**Issue by lindatothova** [kbss-cvut/termit-ui#472]
Vzhledem k zavedení highlight režimu v anotátoru, navrhujeme tomu přizpůsobit grafiku anotátoru takto:

![image](https://github.com/kbss-cvut/termit-ui/assets/80691594/75fc3246-552b-4bac-b21b-1ebd699807d2)

- to, co není návrh, má barevnou výplň (standardní režim)
- výskyty pojmů mají rámeček - odlišný pro návrh a nenávrh (aby byly v highlight režimu vidět a rozlišil se návrh a nenávrh)
- tím by mělo být zajištěno, že jak ve se standardním zobrazení, tak v highlight režimu bude návrh výskytu méně vizuálně výrazný než reálný výskyt

**Comment by ledsoft** [comment]
@lindatothova 
Trochu problém vidím v tom, že se vizuálně téměř nedá odlišit navrhovaný výskyt existujícího a nového pojmu - liší se pouze barvou tečkované čáry, viz:
![image](https://github.com/kbss-cvut/termit-ui/assets/2676156/f6510391-d2ac-4a59-a93b-2eb12dcf9cf3)
Ale možná je to jen moje barvoslepost...
Ještě zkouším použití původních barev, ale u návrhů nižší saturaci, aby nebyly tak výrazné:
![image](https://github.com/kbss-cvut/termit-ui/assets/2676156/008dce73-fe89-49ce-b1e6-849417ce05c3)

@MichalMed Co si o tom myslíš ty?

**Comment by lindatothova** [comment]
Díky za ukázku. Za nás ta první varianta (bez výplně) není špatná. Ta druhá varianta by také šla, jen bychom tam ještě tu saturaci výplně lehce snížili.

**Comment by ledsoft** [comment]
Tak ještě jedna varianta. Menší saturace pro návrhy, navíc návrhy existujících pojmů mají čárkované ohraničení:
![image](https://github.com/kbss-cvut/termit-ui/assets/2676156/bd8b763d-31b2-4157-b101-b0d340feb552)

**Comment by MichalMed** [comment]
měse nejvíc líbí ta původní varianta v nižší saturaci, ale o tomhle si musí rozhodnout zákazník :) @lindatothova

**Comment by lindatothova** [comment]
Díky za další variantu, zas nás to trochu posunulo a na základě toho jsme došli snad už k finálnímu návrhu:

![image](https://github.com/kbss-cvut/termit-ui/assets/80691594/7072fe2e-c3aa-4993-98e2-2febeeac6c11)

Jak jsem o tom přemýšleli: nebylo by vhodné tam mít 3 typy ohraničení, takže ohraničení návrhů buď nechat obojí tečkovaně nebo obojí změnit na čárkované. Pokud by to bylo čárkovaně (tedy celkově výrazněji), tak už by byla potom výplň zbytečná. Čárkované ohraničení by pomohlo lepšímu rozlišení v highlight režimu.

@ledsoft prosím, vytvoříš nám k této poslední variantě ještě ukázku? Ať to raději vidíme v praxi.

**Comment by ledsoft** [comment]
@lindatothova Vypadá to takto:
![image](https://github.com/kbss-cvut/termit-ui/assets/2676156/cf9d9d47-4d19-4ed0-9242-3bcb51bc75c7)

**Comment by lindatothova** [comment]
Děkujeme za ukázku. Mě tohle přijde jako dobré řešení. Počkejme prosím ještě na názor kolegyně za ÚAP. Zítra to tedy ještě potvrdím.

**Comment by ledsoft** [comment]
@lindatothova Nasazeno na development, ať to můžete vyzkoušet v reálu. Pokud budete mít připomínky, dejte vědět.

**Comment by lindatothova** [comment]
@ledsoft Potvrzuji, že tato vizualizace nám vyhovuje, děkujeme.
