### ISSUE TITLE
Možnost nezobrazovat neznámé pojmy v anotátoru

### ISSUE THREAD

**Issue by ledsoft** [kbss-cvut/termit-ui#473]
# Popis
Anotátor by měl umožňovat skrytí návrhů nových pojmů. Těch může být v řadě případů mnoho a uživatele matou či mu překáží.

# Užitečnost

1. zmíněný scénář bez navrhované funkce realizovat nelze 
****

**Comment by ledsoft** [comment]
@lukaskabc Ještě máme zpětnou vazbu od IPR - kdyby tlačítko legendy mohlo indikovat, že některé výskyty jsou vyfiltrované. Nějakou kombinací zvýraznění + tooltipu.

**Comment by lindatothova** [comment]
Vzhledem k implementovanému řešení, kdy lze skrýt/zobrazit jakoukoliv položku legendy (tedy nejen návrhy výskytů, ale také samotné výskyty), je potřeba ještě ošetřit situaci, kdy mám skrytý určitý typ výskytů a zároveň tento typ výskytu v anotátoru chci vytvořit (ať už označením textu nebo potvrzením návrhu výskytu stávajícího/nového pojmu). Předpokládám, že tato akce by neměla být dovolena + uživatel by měl být odkázán na změnu nastavení filtru legendy.

**Comment by ledsoft** [comment]
Pokud jde o potvrzení návrhu, ty stejně uživatel neuvidí, takže to podle mě není problém. Co se týče označení nového výskytu (ať už definice či jen pojmu), pak by asi dávalo smysl automaticky při to resetovat příslušný filtr, ne?

**Comment by lindatothova** [comment]
@ledsoft promiň, nějak mi tento komentář utek..

> Pokud jde o potvrzení návrhu, ty stejně uživatel neuvidí, takže to podle mě není problém. 

ano, tato situace je úplně ok!

> Co se týče označení nového výskytu (ať už definice či jen pojmu), pak by asi dávalo smysl automaticky při to resetovat příslušný filtr, ne?

- souhlasím s řešením pomocí resetu konkrétního filtru, to bude nejjednodušší
- nyní se anotátor chová tak, že pokud označím nový výskyt existujícího pojmu v režimu vypnutého zobrazení výskytů existujících pojmů, potom po vrácení do režimu zobrazení výskytů existujících pojmů všechny dříve označené existující výskyty zmizí a zůstane jen ten poslední vytvořený (obdobně se to myslím chová i u výskytů definic)
- stejné řešení s resetem filtru by se mělo použít také v situaci, kdy výskyt existujícího pojmu vzniká potvrzením návrhu výskytu stávajícího/nového pojmu (a uživatel je v režimu vypnutého zobrazení výskytů existujících pojmů)

**Comment by ledsoft** [comment]
@lukaskabc Tak prosím ještě o úpravu dle komentáře výše.

**Comment by lindatothova** [comment]
Schváleno i ze strany UAP - moc je jim líbí ta klikatelná legenda, tedy vypnutí zobrazení libovolné položky dle potřeby.
