### ISSUE TITLE
Umožnit správci smazat i neprázdný slovník

### ISSUE THREAD

**Issue by ledsoft** [kbss-cvut/termit-ui#486]
# Popis
Jako správce slovníku někdy potřebuji celý slovník smazat. V současné době to vyžaduje nejprve po jednom odstranit všechny pojmy, které obsahuje, a pak jej smazat. Chtěl bych mít možnost slovník smazat i když není prázdný za předpokladu, že na jeho pojmy neexistují vazby z jiných slovníků.

# Využití
Pro správce slovníků či při testování/vytváření dočasných testovacích slovníků.

# Užitečnost

2. zmíněný scénář lze bez funkce realizovat, ale zdržuje mě to
****

**Comment by ledsoft** [comment]
@MichalMed Co myslíš?

**Comment by MichalMed** [comment]
1) mazat může jen admin
2) slovník nesmí mít vazby na jiné slovníky
3) před smazáním musí být upozornění s následky (klidně i opatření jako při mazání repa v GH, kde je potřeba napsat název repa)

**Comment by ledsoft** [comment]
1. Admin + uživatel s právem správy slovníku (např. jeho autor)
