### ISSUE TITLE
Anotátor ignoruje mezery okolo řetězců ve stylu bold

### ISSUE THREAD

**Issue by lindatothova** [kbss-cvut/termit-ui#566]
# Popis problému
Pokud text html dokumentu v Termitu obsahuje části textu napsané tučně,
potom po spuštění textové analýzy v anotátoru
zmizí mezery na začátku a na konci bold řetězce.

Např.: https://termit.fel.cvut.cz/ipr/#/vocabularies/slovn%C3%ADk-%C3%BAzemn%C4%9B-analytick%C3%BDch-podklad%C5%AF-hl.-m.-prahy-%C3%BAap-2024/document/uap2024_0100_textknihy_cistopis_portal.html?namespace=https://slovn%C3%ADk.gov.cz/generick%C3%BD/&fileNamespace=https://slovn%C3%ADk.gov.cz/generick%C3%BD/slovn%C3%ADk-%C3%BAzemn%C4%9B-analytick%C3%BDch-podklad%C5%AF-hl.-m.-prahy-%C3%BAap-2024/document/soubor/

**Comment by ledsoft** [comment]
Fixed by updating outdated version of Annotace on production.
