### ISSUE TITLE
Excel import jazykové mutace

### ISSUE THREAD

**Issue by lindatothova** [kbss-cvut/termit-ui#581]
# Popis
Jako uživatel Termitu
potřebuji ke stávajícím pojmům ve slovníku doplnit překlady vícejazyčných atributů a to hromadně formou Excel importu.

# Využití
Vytvoření anglické mutace slovníku ÚAP, případně dalších.

**Comment by ledsoft** [comment]
Návrh funkcionality:
- import bude vyžadovat buď identifikátor pojmu nebo přesnou shodu názvu (`skos:prefLabel`) v primárním jazyce na prvním sheetu.
- Budou importovány pouze překlady atributů (název, synonyma, vyhl. texty, definice, poznámka, příklady) u nalezených existujících pojmů. Žádné nové pojmy nevzniknou, nedojde k úpravě stávajících dat či importu nových vztahů apod.
